### ISSUE TITLE
Do not chown on startup

### ISSUE THREAD

**Issue by cerebrate** [bitnami/bitnami-docker-dokuwiki#100]
Is there a way to avoid/bypass the various ownership-changes carried out by default by the image on startup?

The data directory for my DokuWiki instance happens to be located on a NAS shared over NFS, and given the configuration attempts to change ownership and permissions of these files always fail with an "Operation not permitted" error. While this in itself is not a problem (the actual operation of the wiki is not impaired), the 30-plus minutes it adds to container startup while trying and failing to do so is unbearable.

**Comment by Mauraza** [comment]
Hi @cerebrate,

That part appears in https://github.com/bitnami/bitnami-docker-dokuwiki/blob/fc4e31a1a9f3cdacca83596b49dfc5f2450dd4e2/20200729/debian-10/rootfs/opt/bitnami/scripts/dokuwiki/postunpack.sh#L27-L34

This is done to make sure that everything will have the correct permissions.

You can try to [customize this image](https://github.com/bitnami/bitnami-docker-dokuwiki#customize-this-image)
