### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by SebSept** [bitnami/bitnami-docker-dokuwiki#104]
### Name and Version

bitnami/dokuwiki   20200729

### What steps will reproduce the bug?

on "Linux bananapi 5.10.60-sunxi #21.08.2 SMP Tue Sep 14 16:28:44 UTC 2021 armv7l GNU/Linux"
with docker "Docker version 20.10.12, build e91ed57"
as a non root user
with the docker-compose file proposed on github's readme,
`docker-compose up` :

```
seb@bananapi:~:docker-compose up          
Starting seb_dokuwiki_1 ... done
Attaching to seb_dokuwiki_1
dokuwiki_1  | standard_init_linux.go:228: exec user process caused: exec format error
seb_dokuwiki_1 exited with code 1
```

any idea to fix this ?

### What do you see instead?

```
seb@bananapi:~:docker-compose up          
Starting seb_dokuwiki_1 ... done
Attaching to seb_dokuwiki_1
dokuwiki_1  | standard_init_linux.go:228: exec user process caused: exec format error
seb_dokuwiki_1 exited with code 1
```

**Comment by SebSept** [comment]
maybe because my proc is 32 bits ?
```
lscpu
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A7
Stepping:            r0p4
CPU max MHz:         960.0000
CPU min MHz:         144.0000
BogoMIPS:            50.52
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
```

**Comment by SebSept** [comment]
this image does not support arm architecture

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
