### ISSUE TITLE
Backup steps seems wrong

### ISSUE THREAD

**Issue by imRichardNg** [bitnami/bitnami-docker-dokuwiki#29]
Hi,

The backup steps outlined in https://github.com/bitnami/bitnami-docker-dokuwiki#backing-up-your-application seems wrong.

`docker cp` is supposed to copy the files from/to host/container.

Maybe the team can clarify.

Best Regards!

**Comment by javsalgar** [comment]
Hi, 

Thanks for reporting the issue. We are working on fixing the guide with the proper steps.
