### ISSUE TITLE
enable logging with persistence

### ISSUE THREAD

**Issue by sgalam** [bitnami/bitnami-docker-dokuwiki#38]
I'm trying to enable the apache logging into persistent volume:

created a directory named "logs" and modified the apache/conf/httpd.conf

```
< ErrorLog "logs/error_log"
---
> ErrorLog "/bitnami/logs/error_log"
304c304
<     CustomLog "logs/access_log" common
---
>     CustomLog "/bitnami/logs/access_log" common
```
all seems working fine. But if I destroy the container (docker rm ID) and create it again.
it fail after some seconds
```
5189ea86abd9        bitnami/dokuwiki:latest   "/app-entrypoint.sh …"   About a minute ago   Exited (0) 43 seconds ago                       dokuwiki
```
no errors on logs.

what is the best way to enable logging on this image and why it's crashing in this way? Ideas?

**Comment by juan131** [comment]
Hi @sgalam 

I'm afraid you cannot do it with the **access_log**. You could do it with the **error_log** but the Nami Apache module will complain if he cannot access the **access_log** at `/opt/bitnami/apache/logs/access_log`.

You could try the following workaround:

 * Create the log files under */bitnami/logs/*
 * Modify the app-entrypoint.sh (https://github.com/bitnami/bitnami-docker-dokuwiki/blob/master/0/rootfs/app-entrypoint.sh) so you substitute the the files */opt/bitnami/apache/logs/access_log* and */opt/bitnami/apache/logs/error_log* with Symbolic links to the ones created at */bitnami/logs/*. Add this logic after the Apache initialisation.

**Comment by sgalam** [comment]
Hi @juan131  thanks for the explanation! 
I would like to use this image in a production enviroment and I need to archive access/error logs.
Is there a best practice defined in your image for do it?

**Comment by tompizmor** [comment]
Hello @sgalam,

I have tried using the following `app-entrypoint.sh` and it seems to work fine.

```
#!/bin/bash -e

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/init.sh" ]]; then
    nami_initialize apache
    if [ ! -d /bitnami/apache/logs ]; then
        info "Persisting apache logs directory... "
        mv /opt/bitnami/apache/logs /bitnami/apache/logs
        ln -s /bitnami/apache/logs /opt/bitnami/apache/logs
    else
        info "Recovering apache logs... "
        rm -rf /opt/bitnami/apache/logs
        ln -s /bitnami/apache/logs /opt/bitnami/apache/logs
    fi
    nami_initialize php dokuwiki
    info "Starting dokuwiki... "
fi

exec tini -- "$@"
```

Can you create a custom image and see if it works as you would expect?
