### ISSUE TITLE
setting the timezone

### ISSUE THREAD

**Issue by maja68** [bitnami/bitnami-docker-dokuwiki#43]
Hi there,

it would be nice to be able to set the timezone via a variable as the time is used to generate the modified time stamp.
I tried to set the timezone via 'timedatectl set-timezone Europe/Berlin' but failed as 'timedatectl' is not available.

### Suggestion:
**variable:** `TZ`
**default value:** `Etc/UTC` (same as now)

But unfortunately I have no glue how to set this on the command line.

Cheers

**Comment by juan131** [comment]
Based on this solution:

https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes

You can add the env. variable **TZ** with your timezone. Then you can modify the **[app-entrypoint.sh](https://github.com/bitnami/bitnami-docker-dokuwiki/blob/master/0/rootfs/app-entrypoint.sh)** script so you add the command below before initialising Dokuwiki:

```
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

**Comment by maja68** [comment]
thanks for your comment @juan131 !
I added the environment variable **TZ** and add the command to create the link to my defined timezone in the app-entrypoint.sh and restartet the container.
I checked the `/etc/timezone` and this was set to the value defined in **$TZ**.
Unfortunately this has no effect on the time used by DokuWiki.

my modified `/app-entrypoint.sh` below
```
#!/bin/bash -e
. /opt/bitnami/base/functions              
. /opt/bitnami/base/helpers             

#setting the timezone
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/init.sh" ]]; then
  nami_initialize apache php dokuwiki 
  info "Starting dokuwiki... " 
fi

exec tini -- "$@"
```

As the above said was not successful I thought may be DokuWiki uses an own configuration. And right they do, see https://www.dokuwiki.org/tips:timezone.

As described in the link I added the `conf/local.protected.php`:
```php
<?php
date_default_timezone_set("Europe/Berlin"); 
```

and it works as desired. 😀 

Sorry to disturb you guys as my topic is a pure DokuWiki issue and not really of the container. 

**But still**, may be its possible to create the `conf/local.protected.php` according to an environment variable like TZ in `/app-entrypoint.sh` ? Does this makes sense for anyone?

**Comment by juan131** [comment]
Great!! I am glad you were able to solve the issue setting it in the the **local.protected.php** file. Regarding adding an environment to configure the TimeZone, I think it could be interesting.

Please feel free to do a PR including this possibility.

**Comment by maja68** [comment]
Thanks again for your help. I am new to docker and GitHub. Need figure out how to do and then I shall come back.
