### ISSUE TITLE
Need update to 2018-04-22 "Greebo" version

### ISSUE THREAD

**Issue by sestegra** [bitnami/bitnami-docker-dokuwiki#44]

**Comment by carrodher** [comment]
We have a task for work on this new DokuWiki version. I can not give you an exact publication date, but it will be available during next few weeks.

**Comment by carrodher** [comment]
Hi, new DokuWiki version was released. You can find it at
https://github.com/bitnami/bitnami-docker-dokuwiki/releases/tag/0.20180422.201805030840-r1
