### ISSUE TITLE
(Solved) Permissions issues on attached volumes with NFS Shares on Docker Swarm. 

### ISSUE THREAD

**Issue by mauvehed** [bitnami/bitnami-docker-dokuwiki#46]
**Description**

Fresh container, followed directions at https://hub.docker.com/r/bitnami/dokuwiki/

**Steps to reproduce the issue:**

1. curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-dokuwiki/master/docker-compose.yml > docker-compose.yml
2. Modified ports (see below)
3. Modified volumes (see below)
4. docker-compose up -d

```
    ports:
      - '8050:80'
      - '8051:443'
    volumes:
      - '/mnt/titan/docker/dokuwiki/data:/bitnami'
```

**Describe the results you received:**

Container stops running after 2 minutes, using "docker container logs dokuwiki_dokuwiki_1" shows the following

$ sudo docker container logs dokuwiki_dokuwiki_1

Welcome to the Bitnami dokuwiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues

```
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing dokuwiki
dokuwik INFO  Passing wizard, please be patient
Error executing 'postInstallation': No INPUT matching 'd[title]'
```

**Describe the results you expected:**

Everything to come up as normal and load the web server

**Additional information you deem important (e.g. issue happens only occasionally):**

This was 100% fresh pull of this container, never used it before.

**Version**

- Output of `docker version`:

```
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.10.1
 Git commit:    7390fc6
 Built: Wed Apr 18 01:23:11 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   7390fc6
  Built:        Wed Feb 28 17:46:05 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

- Output of `docker info`:

```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 2
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: r4n2uu32mgasdmad7kuabdgyu
 Is Manager: true
 ClusterID: u20pyboy3lsjqkb4t3dpe34l3
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: X.X.X.X
 Manager Addresses:
  X.X.X.X:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: v0.13.0 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-20-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.42GiB
Name: marvin
ID: Q6AL:4ZVD:4HKN:D24Y:GAKT:WQTI:CI6D:VJ6Q:ODVR:QF7U:AWVF:XVOM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Brand new OS install, brand new Docker install, only portainer is running besides this container.

**Comment by juan131** [comment]
The first time you run `docker-compose up` it seems the container had some issue during the initialisation and it could not pass successfully the Wizard. See a normal initialisation output: 

```
Welcome to the Bitnami dokuwiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing dokuwiki
dokuwik INFO  Passing wizard, please be patient
dokuwik INFO
dokuwik INFO  ########################################################################
dokuwik INFO   Installation parameters for dokuwiki:
dokuwik INFO     username: superuser
dokuwik INFO     user fullname: Full Name
dokuwik INFO     Password: **********
dokuwik INFO     Email: user@example.com
dokuwik INFO     Wiki Name: Bitnami DokuWiki
dokuwik INFO   (Passwords are not shown for security reasons)
dokuwik INFO  ########################################################################
dokuwik INFO
nami    INFO  dokuwiki successfully initialized
INFO  ==> Starting dokuwiki...
```

The second it used your persisted data but you found an error since the data persisted was incomplete (due to the error during initialisation). Could you please remove that persisted data and retry? I just want to discard it was a random issue with the Wizard.

**Comment by mauvehed** [comment]
Exact same results.

`$ sudo docker container logs -f dokuwiki_dokuwiki_1

Welcome to the Bitnami dokuwiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing dokuwiki
dokuwik INFO  Passing wizard, please be patient
Error executing 'postInstallation': No INPUT matching 'd[title]'
`

I blew away the container, the image, re-ran the curl command (copy pasted from hub.docker.com) modified the docker-compose with my adjusted ports and volume, ran docker-compose up -d and checked the log, as seen above.

**Comment by mauvehed** [comment]
So it worked on a different Ubuntu Bionic box. So now the question is, what's different?

```
$ sudo docker container logs dokuwiki_dokuwiki_1

Welcome to the Bitnami dokuwiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing dokuwiki
dokuwik INFO  Passing wizard, please be patient

```

**Comment by mauvehed** [comment]
On the system that worked:

```
$ sudo docker --version
Docker version 17.12.1-ce, build 7390fc6
$ sudo docker-compose --version
docker-compose version 1.17.1, build unknown
```

On the system that didn't work

```
$ docker --version
Docker version 17.12.1-ce, build 7390fc6
$ docker-compose --version
docker-compose version 1.17.1, build unknown
```

**Comment by mauvehed** [comment]
So the only diff between the two hosts was the the host that fails is storing persistent data on a volume on a CIFS share via NAS. When I attempted to reproduce the same steps using /tmp, it worked.

So why would storing the config and other data on a network share cause it to fail the way it is?

**Comment by juan131** [comment]
Hi @mauvehed 

Does the volume you mounted using your CIFS share had the same permissions as the volume used mounting your **/tmp**? Could you please check the ownership/permissions on both file systems and share them with me?

**Comment by mauvehed** [comment]
This was a whirlwind of complications I have no sorted out.

- CIFS v2+ does nasty things with file permissions whereas my old Linux Samba server was v1 and did not have issues supporting Un*x file permissions.
- I moved to NFS to resolve these issues
- The container now starts and runs properly (see below)

If anyone else encounters this and is mount via file share (specifically SMB/CIFS v2+, just switch to NFS and save yourself the hell.  Or let me know how this can be done (can it?) via v2+

Welcome to the Bitnami dokuwiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues

```
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing dokuwiki
dokuwik INFO  Passing wizard, please be patient
dokuwik INFO
dokuwik INFO  ########################################################################
dokuwik INFO   Installation parameters for dokuwiki:
dokuwik INFO     username: superuser
dokuwik INFO     user fullname: Full Name
dokuwik INFO     Password: **********
dokuwik INFO     Email: user@example.com
dokuwik INFO     Wiki Name: Bitnami DokuWiki
dokuwik INFO   (Passwords are not shown for security reasons)
dokuwik INFO  ########################################################################
dokuwik INFO
nami    INFO  dokuwiki successfully initialized
INFO  ==> Starting dokuwiki...
```

**Comment by mauvehed** [comment]
I spoke too soon. I misconfigured the path and it set /config to local disk instead of the NFS share. When moved to the NFS share I get this error

`Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/dokuwiki/data'`

Which is odd because it appears to fail to chown inside the container. I'll investigate further.

**Comment by mauvehed** [comment]
So https://github.com/kubernetes-incubator/external-storage/issues/104 lead me to believe this may be a root squash issue. So I temproarily disabled root squash by setting no_root_squash on the NFS share (don't do this: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Security_Guide/s2-server-nfs-noroot.html) and yet, the container still fails.

Now with two errors!

```
Welcome to the Bitnami dokuwiki container                                                                                                                                                     
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki                                                                                                   
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues                                                                                               
                                                                                                                                                                                              
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing dokuwiki
Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/dokuwiki/data'

Welcome to the Bitnami dokuwiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues

nami    INFO  Initializing dokuwiki
Error executing 'postInstallation': ENOENT: no such file or directory, open '/opt/bitnami/apache/conf/vhosts/dokuwiki-vhost.conf'
```

**Comment by juan131** [comment]
Hi @mauvehed 

Could you please follow the instructions described on the blog below?

https://engineering.bitnami.com/articles/scaling-wordpress-in-kubernetes.html

They are intended for Dokuwiki but they're totally valid for WP. The steps necessary to install a NFS provider using the Helm chart and then use NFS RWX volumes on your containers.

**Comment by mauvehed** [comment]
I'm not actually using kubernetes. That link just happened to be one that may shed insight into my challenge. I'm using Docker in a single node swarm mode. Technically docker-compose doesn't push to swarm but this is just a single instance and for now is purely a test.

**Comment by mauvehed** [comment]
Let's be 100% clear, I don't think this is in anyway an issue with the bitnami dokuwiki container. If you'd prefer to close this issue that's fine. Otherwise I'll continue to use it as a place to log my journey and hopefully a solution for others who may stumble across similar issues.

**Comment by juan131** [comment]
Hi @mauvehed 

I think it's good to continue the discussion here so others users experiencing similar issues can find easily the solutions you found for this specific problem. 

If you don't mind, I'll rename the issue so it's more accurate with the topic being discussed.

**Comment by mauvehed** [comment]
@juan131 so while i don't have a fix for dokuwiki, I ran into similar problems with a few other docker hub images (specifically ones from linuxserver (https://hub.docker.com/r/linuxserver/). One thing about their containers that allowed me to solve the problem, is that I can pass in a UID and GID. The signifigance of this is that it means the user inside the container matches the same uid/gid I'm squashing on my NFS share. Thus, no permissions errors. Many of their containers attempt a "chown" during startup and were failing until I set the proper uid/gid in the "docker create". I suspect something similar is going on in that the bitnami image is trying to use a uid/gid that is being rejected by the NFS share. 

I'll continue to dig and see what else I can come up with. I may have to modify the actual Dockerfile or rebuild some of the other base images, but I'm hoping to avoid that. Otherwise, I may have to adjust how I export my NFS share.

**Comment by juan131** [comment]
Hi @mauvehed 

We're using non-root containers on other images, e.g. NGINX, MariaDB or Ghost. You can take a look to their README.md files and you'll find they use 1001 as UID/GID.

Thanks for reporting this issue with NFS on Docker Swarm. I'll share your insights with team so we can discuss about whether we should extend the non-root solution to other images or not.

**Comment by mauvehed** [comment]
I appreciate your patience in letting me work this out! I'll look further at those other images as well. Thank you!

**Comment by fognar777** [comment]
I am having a very similar issue to what Mauvehed had, but I trying to save my persistent data to a folder under the root filesystem. I am able to launch the container just fine if I don't include a persistent volume, but it fails to load if I do. I am running this as a docker command FYI

**Comment by fognar777** [comment]
@fognar777 So I managed to figure out a work around that got me up and running. I started the container with the persistent volume on a secondary disk on my system. For whatever reason it worked there and everything initialized. I then stopped and removed the container, moved the files in the volume back to my root drive then started the container pointing to that location. 
A little messy but I should only have to do it once right?

**Comment by juan131** [comment]
I don't understand very well what was the issues and what were you trying to @fognar777 

- Are you moving the data volume from one Dokuwiki container to another?
- Could you please provide more details?

**Comment by juan131** [comment]
The `no_root_squash` should allow the root user (the one initializing Dokuwiki) to do `chmod/chown` operations in the NFS volume. See:

https://serverfault.com/questions/212178/chown-on-a-mounted-nfs-partition-gives-operation-not-permitted

Could you try setting the `anonuid/anongid` to `0`?

**Comment by bedcruncher** [comment]
@juan131 @mauvehed 
I have changed my NFS export options to 
`rw,sync,no_root_squash,anonuid=0,anongid=0,no_acl` 
and also set my permissions on the remote disk to 
`drwxrwxrwx.  5 root root  4096 Apr 10 08:21 docker`

When I spin the container up it is able to create the files on external volume, but still fails with the same error message 
```docker logs -f d8176f72cf91

Welcome to the Bitnami dokuwiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues

nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing dokuwiki
Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/dokuwiki/data'
```
Here is the results of docker volume inspect on that volume that I created
```[
    {
        "CreatedAt": "2019-04-10T08:21:17-05:00",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/100000.100000/volumes/dokuwiki/_data",
        "Name": "dokuwiki",
        "Options": {
            "device": ":/nfsshare/docker",
            "o": "addr=EXTERNAL_IP_HERE,soft,nolock,vers=3,rw",
            "type": "nfs"
        },
        "Scope": "local"
    }
]
```

**Comment by fognar777** [comment]
> I don't understand very well what was the issue and what were you trying to @fognar777
> 
> * Are you moving the data volume from one Dokuwiki container to another?
> * Could you please provide more details?
@juan131 

I was trying to create a new dokuwiki container from scratch, but it wouldn't initialize and run when I used a persistent volume on a sub directory off my main OS drive. Here is the volume mount that I was trying for reference. 
-v /docker/wiki:/bitnami
When using that mount point I got the same errors that mauvehed described during the containers first startup, with the above directory blank to start. Also much like him I would get a different error if I restarted the container, but it would still fail to load correctly. 
> Error executing 'postInstallation': No INPUT matching 'd[title]'

What I ended up doing to work around the issue was start the container with a volume mount pointing to a blank folder on one of my secondary drives. The container started with that mount point and it allowed the setup/startup process to finish. I then stopped the container and moved the contents of that folder to my main OS drive and now the container is running happily. 

I've started many different containers with persistent volume mounts in the same location on my OS drive so I am not sure why this one wouldn't startup correctly. But I am up and running now and already well into building myself a little wiki, so I can't complain.

**Comment by juan131** [comment]
Great @fognar777 ! I'm glad you found a workaround for your problem! 

@bedcruncher regarding your issue with the NFS server I'm afraid I'm not an expert on NFS and it depends on the implementations of the NFS provider.

> I am using a HA NFS setup shared via Pacemaker/Corosync

What HA NFS setup are you using? 
Did you try contact the developers of that setup? They might have more information about the corresponding options to configure so you can perform `chmod/chown` operations in the NSF shares.

**Comment by bedcruncher** [comment]
@juan131 
I am using Pacemaker/Corosync with a SCSI fencing disk. My NFS implementation is the normal one that is in the standard Centos REPOs. 
On the Docker Swarm Master:
```
rpm -qa | grep nfs
libnfsidmap-0.25-19.el7.x86_64
nfs-utils-1.3.0-0.61.el7.x86_64
nfs4-acl-tools-0.3.3-19.el7.x86_64
```
On one of the NFS servers:
```
rpm -qa | grep -e "nfs\|pcs\|coro\|pace"
corosync-2.4.3-4.el7.x86_64
pacemaker-cli-1.1.19-8.el7_6.4.x86_64
libnfsidmap-0.25-19.el7.x86_64
pacemaker-libs-1.1.19-8.el7_6.4.x86_64
pcs-0.9.165-6.el7.centos.1.x86_64
nfs-utils-1.3.0-0.61.el7.x86_64
corosynclib-2.4.3-4.el7.x86_64
pacemaker-1.1.19-8.el7_6.4.x86_64
pacemaker-cluster-libs-1.1.19-8.el7_6.4.x86_64
nfs4-acl-tools-0.3.3-19.el7.x86_64
```
If I mount the NFS share on one of the Docker Swarm Nodes using the command ` mount 172.16.0.40:/nfsshare/docker /mnt` and then run the CHOWN command I don't get an error same thing if I skip the mount command and do the same thing directly on the NFS server. It's only when spinning up the DOKUWIKI container using the NFS volume that it gives the EPERM error about CHOWN.

**Comment by juan131** [comment]
Hi @bedcruncher 

The Bitnami Dokuwiki image uses [Nami](https://github.com/bitnami/nami) (a Node.js CLI tool) to initialize Dokuwiki. To do so, the initialization logic is written in some components known as Nami modules.

These Nami modules uses the library below to perform "chown" operations:

https://github.com/bitnami/nami-utils/blob/master/lib/file/chown.js

These libraries relies on the Node.js moduels **["fs"](https://nodejs.org/api/fs.html)** library:

https://nodejs.org/api/fs.html#fs_fs_chown_path_uid_gid_callback

Could you try (using Node.js and the function `fs.chmod()`) to perform a chown operation on a NFS share provided by your NFS server? It might be a problem related to how Node.js implements this function.

**Comment by bedcruncher** [comment]
So I got node installed on one of my Swarm servers and ran the following script that I wrote on a file that was stored on the NFS share that was mounted at /mnt. 
```
var fs = require('fs');
fs.chown("/mnt/test.txt", 10000, 10000, (err) => {
 if (err) { throw err; }
});
```
The pre-script execution permissions
```
ls -la /mnt/
total 20
drwxrwxrwx.  6 root   root   4096 Apr 12 14:50 .
dr-xr-xr-x. 18 root   root    235 Jan 18 12:37 ..
drwxr-xr-x.  3 100000 100000 4096 Apr 10 08:21 apache
drwxr-xr-x.  5 100000 100000 4096 Apr 10 08:22 dokuwiki
drwxr-xr-x.  3 100000 100000 4096 Apr 10 08:21 php
drwxr-xr-x.  2 root   root   4096 Apr 12 14:50 test.txt
```
Post execution permissions
```
 ls -la /mnt/
total 20
drwxrwxrwx.  6 root   root   4096 Apr 12 14:50 .
dr-xr-xr-x. 18 root   root    235 Jan 18 12:37 ..
drwxr-xr-x.  3 100000 100000 4096 Apr 10 08:21 apache
drwxr-xr-x.  5 100000 100000 4096 Apr 10 08:22 dokuwiki
drwxr-xr-x.  3 100000 100000 4096 Apr 10 08:21 php
drwxr-xr-x.  2  10000  10000 4096 Apr 12 14:50 test.txt
```

**Comment by juan131** [comment]
Thanks for sharing the results @bedcruncher 

What Node.js version are you using? 

```bash
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-dokuwiki/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
$ docker-compose exec dokuwiki /opt/bitnami/nami/runtime/node --version
v8.11.3
```

Could you retry the test with the Node.js version used by Nami (8.11.3)?

**Comment by bedcruncher** [comment]
@juan131 
The version that came with the official Centos EPEL repo is v6.16.0. I will see if I can get a more up to date version and report back that result.

**Comment by juan131** [comment]
Hi @bedcruncher 

Does the test also work when using the Node.js function `fs.chownSync()`?

Another alternative would be using the `nami console`. You could run a container such as Minideb Extras (bitnami/minideb-extras), open a `nami console` and run the `$file.chown` command. Sth like:

```bash
$ docker run -it -v $(pwd):/data bitnami/minideb-extras nami console
nami>$file.chown('/data/', 1001, 1001);
```

I'm sorry if the process is being a pain but it's very hard to me to reproduce it on my side without your NFS.

**Comment by bedcruncher** [comment]
@juan131 
Here's the results from that command. Looks like the same issue. 
```
docker run -it -v $(pwd):/data bitnami/minideb-extras nami console
nami> $file.chown('/data/', 1001, 1001);
Error: User '1001' not found
    at _findUser (/opt/bitnami/nami/node_modules/nami-utils/lib/os/user-management/find-user.js:10:11)
    at findUser (/opt/bitnami/nami/node_modules/nami-utils/lib/os/user-management/find-user.js:37:10)
    at getUid (/opt/bitnami/nami/node_modules/nami-utils/lib/os/user-management/get-uid.js:22:25)
    at Object.chown (/opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:64:20)
nami> $file.chown('/data/', 1000, 1001);
Error: Group '1001' not found
    at _findGroup (/opt/bitnami/nami/node_modules/nami-utils/lib/os/user-management/find-group.js:10:11)
    at findGroup (/opt/bitnami/nami/node_modules/nami-utils/lib/os/user-management/find-group.js:37:10)
    at getGid (/opt/bitnami/nami/node_modules/nami-utils/lib/os/user-management/get-gid.js:22:25)
    at Object.chown (/opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:65:20)
nami> $file.chown('/data/', 1000, 1000);
Error: EPERM: operation not permitted, chown '/data/'
    at Object.fs.chownSync (fs.js:1179:18)
    at _chown (/opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:25:14)
    at Object.chown (/opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:80:5)
```
One thing that sticks out in my mind as a possible cause of this and I think I mentioned it before was that I am using the docker namespace remapping and it occurred to me that this might be causing issues with running chown on the volume map. Just a thought.

**Comment by javsalgar** [comment]
This is what I did in order to do the chown

```
○ → docker run -it -v $(pwd):/data bitnami/minideb-extras bash



root@fce5dd57a7b1:/# chown 1001:1001 -R data
```

**Comment by bedcruncher** [comment]
@javsalgar 
I actually did that exact same thing yesterday, but even when doing that I get the following...
```
root@fef9710b69f1:/# ls -la data/
total 8
drwxr-xr-x. 2 bitnami bitnami 4096 Apr 17 14:09 .
drwxr-xr-x. 1 root    root    4096 Apr 18 12:54 ..
-rwxr-xr-x. 1    1001    1001    0 Apr 17 14:09 123
-rw-r--r--. 1    1001    1001    0 Apr 17 14:09 234
-rwxr-xr-x. 1    1001    1001    0 Apr 17 11:59 test
-rwxr-xr-x. 1    1001    1001    0 Apr 17 12:23 test2
-rwxr-xr-x. 1    1001    1001    0 Apr 17 11:59 test3
root@fef9710b69f1:/# chown 1000:1000 -R data
chown: changing ownership of 'data/test2': Operation not permitted
chown: changing ownership of 'data/234': Operation not permitted
chown: changing ownership of 'data/123': Operation not permitted
chown: changing ownership of 'data/test3': Operation not permitted
chown: changing ownership of 'data/test': Operation not permitted
chown: changing ownership of 'data': Operation not permitted
```
The only way I can chown the files is directly on the NFS server. Even if I chmod the files to be 777 I still get the operation not permitted error. I know it is not SELINUX causing issues.
If I change down to a different directory and try the chown command even on the Swarm Master I still get the error. I'm not 100% sure here as to what the issue actually is at this point.

**Comment by javsalgar** [comment]
Hi,

I am afraid that this goes a bit beyond my expertise. We have tested some of our helm charts using, for example, the nfs provisioner chart (https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner) and we did not find issues. I do not know how different the nfs server this chart deploys and yours are, but maybe it contains an option that your setup doesn't. 

Anyways, it would be great if others from the community could share their experience with NFS setups.

**Comment by lionux2** [comment]
I have the same issue with another container package from dokuwiki, and using the docker volume plugin local-persist. Based on my current tries, I think that this is due to the block device format on the nfs point. Strange, as this should work; nfs is doing some abstractions on file level from the block device, and the format on this block device should not cause issues. Still I think this might explain all the trouble we are having. I will try the vfs storage type to confirm, but of course this is not the solution I am looking for.

**Comment by juan131** [comment]
Hi @lionux2 

Thanks so much for sharing your experience with NFS and the Dokuwiki image. Please do not hesitate to share with other users if the VFS storage solves your issue.

As @javsalgar mentioned before we're not experts on NFS (and the different configuration options) so we're not very helpful on helping you to choose the right settings for your NFS servers.
