### ISSUE TITLE
Vulnerable/End of Life OpenSSL

### ISSUE THREAD

**Issue by mauvehed** [bitnami/bitnami-docker-dokuwiki#47]
**Description**

OpenSSL version 1.0.1t is installed and being used by the webserver. This version of OpenSSL is end of life and vulnerable to a number of attacks including SWEET32

- https://mta.openssl.org/pipermail/openssl-announce/2014-December/000000.html
- https://www.openssl.org/news/secadv/20160922.txt
- https://sweet32.info/
- https://github.com/openssl/openssl/commit/41b42807726e340538701021cdc196672330f4db

**Steps to reproduce the issue:**

```
$ docker container exec -it dokuwiki_dokuwiki_1 bash
root@b45c81fe118a:/# openssl version
OpenSSL 1.0.1t  3 May 2016
```

**Comment by mauvehed** [comment]
I couldn't find a "master" bitnami issue t open this against, as I suspect this vuln exists across all images built from the same base. 

I did find this issue reported here though, https://github.com/bitnami/bitnami-docker-mediawiki/issues/66

**Comment by carrodher** [comment]
Currently, we are installing OpenSSL using the system packages, but we are not installing it explicitly, it is installed as a dependency for other packages. 
This means that the version of openssl is the one that uses Debian 8 by default (if you execute `sudo apt-get install openssl` Debian 8 (jessie) installs `1.0.1t`). 
Distros usually use the same version but patch the security vulnerabilities, even the version is `1.0.1t`. Debian should continue patching the libraries for securities.

https://packages.debian.org/jessie/openssl
https://packages.debian.org/search?keywords=openssl
