### ISSUE TITLE
Very slow settings changes

### ISSUE THREAD

**Issue by Informatic** [bitnami/bitnami-docker-dokuwiki#48]
Just a quick note:

By default PHP OpCache is enabled in this image, which makes DokuWiki configuration changes very slow. (60s)

For inital configuration it'd be advised for user to either completly disable `opcache.enable` or reduce `opcache.revalidate_freq` at the bottom of `/bitnami/php/conf/php.ini` inside of the container.

**Comment by Informatic** [comment]
Actually, when I think of it now, it could be somehow fixed properly by blacklisting DokuWiki configuration files...

https://secure.php.net/manual/en/opcache.configuration.php#ini.opcache.blacklist-filename

**Comment by andresbono** [comment]
Hi @Informatic, thanks for your feedback. We will evaluate if we change the cache options for this container.

Did you improve the performance including an opcache blacklist file?

-Andrés B.

**Comment by Informatic** [comment]
I ended up with just reducting `opcache.revalidate_freq`.

The thing is, it's not even a problem of performance - settings page just returns "Settings saved", but the changes are actually applied after `opcache.revalidate_freq` - adding configuration file to blacklist will just never cache it, thus there'll be no need to wait for changes to be properly applied.

I'll check this now and report it back, but I'm 99% sure that's the proper solution.

**Comment by Informatic** [comment]
Yep, this seems to work fine.

1. Create `/bitnami/php/conf/opcache.blacklist` file (i have whole `/bitnami` shared from host, but that doesn't really matter) with following contents:
```/bitnami/dokuwiki/conf/*.php```

2. Add following line at the bottom of `/bitnami/php/conf/php.ini`:
```opcache.blacklist_filename = /bitnami/php/conf/opcache.blacklist```

Now configuration changes take effect instantly.

**Comment by andresbono** [comment]
Hi again @Informatic. Thank you very much for taking the time to describe the steps that you followed to adjust the cache options! 🎉 

As we said, we will evaluate if we change the cache options for this container. In the meantime we will keep the issue opened so other users can be benefited from your contribution.

Thanks again!

-Andrés B.

**Comment by marcosbc** [comment]
Hi @Informatic, starting with `0.20180422.202005011246-debian-10-r68` the container initialization scripts are available in the `rootfs` directory, and they were improved so it is possible for PHP and Apache settings to be set at build time. See: https://github.com/bitnami/bitnami-docker-dokuwiki#020180422202005011246-debian-10-r68

I'm closing this issue for now, since it should be able to workaround this issue without any trouble. However, if you consider this issue is still applicable, let us know and we can re-open it.
