### ISSUE TITLE
Bitnami-dockuwiki - Site Export fails - PHP zip problem? Finished download but failed

### ISSUE THREAD

**Issue by rgleason** [bitnami/bitnami-docker-dokuwiki#51]
Windows10 Local version of Opencpn Wiki
Installed Bitnami-dockuwiki, then installed downloaded Backup files from website. Easy.
Bitnami-dockuwiki - Site Export fails -
Have checked php settings, seems to be enabled.
Have checked all the site export requirements. I believe they are all good.
https://forum.dokuwiki.org/post/62106
"Finished download but failed."

**Comment by marcosbc** [comment]
Hi @rgleason, is this related with the Bitnami Docker image for DokuWiki? If not, if it is related to the Windows installer, please post this question in the [Bitnami Community](https://community.bitnami.com) and we can continue there.

In the meantime, we were able to get the plugin working in a Linux installation by following these instructions:

- In `INSTALLDIR/apps/dokuwiki/htdocs/lib/plugins`: Run the command `git clone git://github.com/tatewake/dokuwiki-plugin-backup.git backup`.
- Change ownership for files (not necessary in Windows): `chown daemon:daemon INSTALLDIR/apps/dokuwiki/htdocs/inc`.
- Edit `INSTALLDIR/apps/dokuwiki/htdocs/lib/plugins/siteexport/conf/default` and change the "debugFile" property, for instance to this value:

        $conf['debugFile'] = "/tmp/debugfile";

- Disable Pagespeed in `INSTALLDIR/apache2/conf/httpd.conf` (not necessary in Windows).

Did this fix your issue?

If this did not fix your issue, and you are not using a Docker image, **please post in the [Bitnami Community](https://community.bitnami.com)** and we will help you there.

Thanks!

**Comment by rgleason** [comment]
I am closing this. I reloaded SiteExport, checked php zip was on, then made new paths and filenames in config for siteexport plugin debug and zip files. I used MS Windows notation for the pathnames and changed from relative to absolute paths.  

It seems to be running now. It has not completed but it is running!
