### ISSUE TITLE
Feature request: Nice URLs on by default

### ISSUE THREAD

**Issue by svenssonaxel** [bitnami/bitnami-docker-dokuwiki#52]
See #49 and #39.

Nice URLs are probably wanted more often than not. It seems the only reason for Dokuwiki not having them turned on by default is that this requires accurate configuration of the web server. Since the web server is included in this container, it is a perfect opportunity to turn nice URLs on by default and alleviate the user from configuring this manually.

I order to achieve this, I believe the following should be done:

- Alter the default for `/bitnami/apache/conf/vhosts/htaccess/dokuwiki-htaccess.conf` to include the appropriate rewrite_mode rules to allow nice URLs.
- Alter the default for `/bitnami/dokuwiki/conf/dokuwiki.php` to set $conf['userewrite'] = '1';
- Check with the dokuwiki development mailing list that there is no security concern in setting userewrite=0 while keeping the rewrite rules active.
- Perhaps update the readme to say that the GUI setting is sufficient to turn nice URLs on/off.

**Comment by juan131** [comment]
Hi @svenssonaxel 

Thanks for creating this issue and summarising so well what we were already discussing on: https://github.com/bitnami/bitnami-docker-dokuwiki/pull/49

As you mentioned, it's necessary to setup a serie of **htaccess** rules in order to use Nice URLs (more information can be found at https://www.dokuwiki.org/rewrite):

> DokuWiki supports two methods for URL rewriting, enabled through the use-rewrite option. One relies on the rewriting capabilities of the webserver; the other one handles rewritten URLs inside DokuWiki.

We could configure the Dokuwiki using the first method so this Dokuwiki image supports URL rewriting by default. @beltran-rubo do you find any reason why shouldn't support it by default?

**Comment by svenssonaxel** [comment]
Regarding the env. variable:

If the htaccess rules are present, both nice and regular URLs will work, regardless of the GUI setting. The only thing the GUI setting does is decide whether nice URLs will be used for the links. This means that as long as there are no security concerns, the htaccess rules can be always on and the user can use the GUI to decide what types of URLs are wanted. I see no need for an env. variable.

**Comment by svenssonaxel** [comment]
Thank you. I agree with you that the impact of the issue is limited.

It's worth mentioning that fixing the issue will likely have little or no impact on existing deployments since the default configuration to be changed is only used at the installation phase when it's copied unto the persistent volume. IIUC, an existing deployment with a persistent volume holding the configuration would not be impacted at all by the change, at least for Apache.

I don't know if the same is true for the Dokuwiki configuration. Would this fix cause nice URLs to be activated for existing deployments that upgrade Dokuwiki version? If this is a problem, it's worth mentioning that this fix will have the same benefits even if the change in `/bitnami/dokuwiki/conf/dokuwiki.php` is not included, i.e. users will still be able to activate nice URLs through GUI only.

**Comment by juan131** [comment]
Hi @svenssonaxel 

> Would this fix cause nice URLs to be activated for existing deployments that upgrade Dokuwiki version?

No, existing deployments will need to configure it by themselves since the "Dokuwiki initialisation" logic is skipped if there's existing data/configuration from previous deployments.

**Comment by svenssonaxel** [comment]
I understand that the initialization logic is skipped. I was referring to the logic for upgrading a configuration from one Dokuwiki version to the next, but maybe no such logic exists. In that case, this is not an issue, and nice URLs can be activated by default.

**Comment by rgleason** [comment]
I don't agree with nice url by default.

**Comment by svenssonaxel** [comment]
@rgleason, do you then agree to include, by default, the necessary Apache configuration to prepare for nice URLs albeit not activate them?

**Comment by juan131** [comment]
Hi @rgleason 

+1 to @svenssonaxel suggestion about configuring Apache to support them.

**Comment by rgleason** [comment]
> @rgleason, do you then agree to include, by default, the necessary Apache configuration to prepare for nice URLs albeit not activate them?

This sounds perfectly ok to me. I am an experienced Dokuwiki user, but do not know inner workings by any means.

**Comment by lordSeaworth** [comment]
I'm all for adding it to the image at least so we can enable it. Just started using this image for my own personal wiki and what I missed right away was nice urls.

So if this could be added in a future release this would be great.

**Comment by juan131** [comment]
Hi @lordSeaworth 

We have at task included in our backlog. As it's possible to workaround this "issue", there are no immediate plans to work on it. Nevertheless, it will be considered for future application versions.

We will update this thread as soon as we have more news.

**Comment by lordSeaworth** [comment]
@juan131 

Thank you. I don't mean people should work on it right away. But since people here were talking about the option. Just thought I would say that I would like it myself.

And thank you. That would be very helpful. Thanks for replying.

**Comment by tasism** [comment]
Since it was mentioned that there are possible workarounds but I didn't manage to find a suggestion, please find here a proposal: keep the Rewrite rules (that would normally go in .htaccess) in a configuration file that is *appended* to the Bitnami configuration file using standard Docker commands (COPY & RUN). Using this allows you to re-build your container automatically and still keep the Rewrite rules.

**docker-compose.yml**

    version: '2'
    services:
      dokuwiki:
        build:
          context: .
        container_name: dokuwiki
        hostname: dokuwiki
        ports:
          - '8080:80'
        volumes:
          - 'dokuwiki_data:/bitnami'
    volumes:
      dokuwiki_data:
        driver: local

**Dockerfile**

    FROM 'docker.io/bitnami/dokuwiki:0-debian-10'
    COPY ./dokuwiki-htaccess-rewrite.conf /opt/bitnami/apache/conf/vhosts/htaccess/dokuwiki-htaccess-rewrite.conf
    RUN cat /opt/bitnami/apache/conf/vhosts/htaccess/dokuwiki-htaccess-rewrite.conf >> /opt/bitnami/apache/conf/vhosts/htaccess/dokuwiki-htaccess.conf

**dokuwiki-htaccess-rewrite.conf**

    <Directory "/opt/bitnami/dokuwiki">
      RewriteEngine on
      #
      RewriteRule ^_media/(.*)              lib/exe/fetch.php?media=$1  [QSA,L]
      RewriteRule ^_detail/(.*)             lib/exe/detail.php?media=$1  [QSA,L]
      RewriteRule ^_export/([^/]+)/(.*)     doku.php?do=export_$1&id=$2  [QSA,L]
      RewriteRule ^$                        doku.php  [L]
      RewriteCond %{REQUEST_FILENAME}       !-f
      RewriteCond %{REQUEST_FILENAME}       !-d
      RewriteRule (.*)                      doku.php?id=$1  [QSA,L]
      RewriteRule ^index.php$               doku.php
      #
      ## Not all installations will require the following line.  If you do,
      ## change "/dokuwiki" to the path to your dokuwiki directory relative
      ## to your document root.
      #RewriteBase /
    </Directory>

**Comment by juan131** [comment]
Hi @svenssonaxel 

Thanks so much for sharing the workaround providing the specific steps to follow, we really appreciate that! It'll be very helpful for the rest of users.

**Comment by marcosbc** [comment]
Hi all, just wanted to let you know that we have just released DokuWiki `20200729.0.0-debian-10-r6` which enables nice/friendly URLs by default.

**Comment by Floyer007** [comment]
Is there a easy way to disable this behaviour?
The new default crashes my current system and I don't really need the new rewrite-default.

`$conf['userewrite'] = 0;`
Seems to have no influence like described here: https://www.dokuwiki.org/rewrite

**Comment by marcosbc** [comment]
Hi @Floyer007, currently we don't have any option for disabling friendly URLs. However, could you describe what particular issues you're having?

We believe it could be related to this Apache httpd configuration: https://github.com/bitnami/bitnami-docker-dokuwiki/blob/master/20200729/debian-10/rootfs/opt/bitnami/scripts/dokuwiki/postunpack.sh#L44

In the meantime while we find a way to implement such flag, you can fork the container and remove the configuration, or mount the following files in your container at runtime without it:

- `/opt/bitnami/apache/conf/vhosts/dokuwiki-vhost.conf`
- `/opt/bitnami/apache/conf/vhosts/dokuwiki-https-vhost.conf`

**Comment by Floyer007** [comment]
Well, after some testing it seems, that I messed up with docker and - _bitnami/dokuwiki:20200729.0.0-debian-10-r6_ isn't the problem.
It actually works fine. Just _:latest_ doesn't work.

I will investigate in it and create a new issue, if necessary.
Thank you for your fast response.

**Comment by marcosbc** [comment]
Thanks for sharing @Floyer007. Could you try and find the problematic Docker image tag? I.e. `20200729.0.0-debian-10-r40`, if it works then `20200729.0.0-debian-10-r39`, and then so on.

Also, what specific error are you getting? Is it failing to deploy? If so you could always try to enable `BITNAMI_DEBUG=true` to get more info.

**Comment by Floyer007** [comment]
Sure. But it will take some time.
I've some other things to do right now.
