### ISSUE TITLE
Environment variables  take no effect

### ISSUE THREAD

**Issue by lebowski42** [bitnami/bitnami-docker-dokuwiki#57]
Hi,

using Environment variables for the dokuwiki container (Like _DOKUWIKI_USERNAME_) has no effect. Always the default values are in use. It looks like, they are hard coded in the Dockerfile (https://hub.docker.com/r/bitnami/dokuwiki/dockerfile ).

Martin

**Comment by tompizmor** [comment]
Hi @lebowski42,

I just tried and it worked fine for me. The env var values you see in the Dockerfile are just the default values but they can be overwritten with docker-compose files or docker CLI.

Most of the env vars only take effect during the first initialization, so it is possible that you initialized Dokuwiki with some values and then try to re-initialize with modified data. In that case, the env vars are ignored. If you want to re-initialize from scratch, you have to clean all the data from the volumes (`docker-compose down -v`) and then deploy it again (`docker-compose up`). 

Check if see you something like the following in the docker logs to be sure you are initializing from scratch:

```
dokuwiki_1  | dokuwik INFO  ########################################################################
dokuwiki_1  | dokuwik INFO   Installation parameters for dokuwiki:
dokuwiki_1  | dokuwik INFO     username: tomas
dokuwiki_1  | dokuwik INFO     user fullname: Full Name
dokuwiki_1  | dokuwik INFO     Password: **********
dokuwiki_1  | dokuwik INFO     Email: user@example.com
dokuwiki_1  | dokuwik INFO     Wiki Name: Bitnami DokuWiki
dokuwiki_1  | dokuwik INFO   (Passwords are not shown for security reasons)
dokuwiki_1  | dokuwik INFO  ########################################################################
```

On the contrary, if you see the following stanza it means you are using restored data:

```
dokuwiki_1  | dokuwik INFO  ########################################################################
dokuwiki_1  | dokuwik INFO   Installation parameters for dokuwiki:
dokuwiki_1  | dokuwik INFO     Persisted data and properties have been restored.
dokuwiki_1  | dokuwik INFO     Any input specified will not take effect.
dokuwiki_1  | dokuwik INFO   This installation requires no credentials.
dokuwiki_1  | dokuwik INFO  ########################################################################
```

I hop it helps!

**Comment by wayne003** [comment]
It helped, thanks
in my case, I use volume bind for persistent data. if you use volume bind, you have to clean it up, otherwise, setting in environment variable will be ignored.

**Comment by tompizmor** [comment]
Correct! Thanks for pointing it out.
