### ISSUE TITLE
How to run dokuwiki with local user permissions?

### ISSUE THREAD

**Issue by romach** [bitnami/bitnami-docker-dokuwiki#58]
I run DokuWiki container with command 

```
docker-compose up -d
```

But when I look at data in volume:

```
ls -lah dokuwiki_data/

drwxrwxr-x 5 romach romach 4,0K лют 18 16:13 .
drwxrwxr-x 3 romach romach 4,0K лют 18 16:13 ..
drwxr-xr-x 3 root   root   4,0K лют 18 16:13 apache
drwxr-xr-x 5 daemon daemon 4,0K лют 18 16:13 dokuwiki
drwxr-xr-x 3 root   root   4,0K лют 18 16:13 php
```
I see that directories have `root` and `daemon` owners. So, I cannot edit these files without `root` permissions.

**How can I run DokuWiki container, so that all directories and files would have host user (`romach`) as owner, so I could edit them locally?**

**Comment by marcosbc** [comment]
Hi @romach, those files are meant to be used by the container, so they need to have proper permissions.

You can always edit them with `sudo` (e.g. with nano `sudo nano apache/conf/httpd.conf`, or other editors like `vim` or `emacs`).

**Comment by Ronaldvr** [comment]
@marcosbc, I ran into the same issue, since I needed to create a mime.local.conf file and the docuwiki documentation mentions that this directory should be writeable too for the superuser:

https://www.dokuwiki.org/install:permissions

So the 'proper' permissions are up to what usage and who administers the server I think.

**Comment by marcosbc** [comment]
Hi @Ronaldvr, during the startup the container configures the permissions for all directories mentioned in that template, so they are properly writable by the DokuWiki web server user.

Note that the user running the DokuWiki web server will likely not match the one in your host OS. Therefore, if you need to create a file from outside of the container, you will later need to run the command below:

    sudo chown 1001:1001 /path/to/volume/file
