### ISSUE TITLE
Cant restore backups?

### ISSUE THREAD

**Issue by thepenguinthatwants** [bitnami/bitnami-docker-dokuwiki#63]
Hi guys!

So I made backups with https://www.dokuwiki.org/plugin:backup plugin

extracted the backupfile which consisted conf, data, lib to the correct place.

When I try to boot my docker-compose image. I cant get it loaded and the errorlog consists.

dokuwiki_1  | Error executing 'postInstallation': ELOOP: too many symbolic links encountered, stat '/bitnami/dokuwiki/lib/images/smileys/local'

**Comment by alemorcuq** [comment]
Hi, @thepenguinthatwants.

Can you give me some step by step instructions to reproduce your issue? How are you deploying ti? Are you using `docker-compose`? It's not very clear to me in your message. For example:

```
extracted the backupfile which consisted conf, data, lib to the correct place.
```

What do you mean by `the correct place`?

Also, note that we already [persist the following directories](https://github.com/bitnami/bitnami-docker-dokuwiki#persisting-your-application):

```
data
conf
lib/plugins
lib/tpl
lib/images/smileys/local
lib/images/interwiki
```

Regards,
Alejandro

**Comment by thepenguinthatwants** [comment]
Hi!

Sorry for my earlier messages that left so much info out.

Here is the compose.

> version: '3'
> services:
> 
>   dokuwiki:
>     image: bitnami/dokuwiki:latest
>     volumes:
>     - '$PWD/dokuwiki:/bitnami'
>     networks:
>       - srv
>     ports:
>       - "8081:80"
>     environment:
>       - DOKUWIKI_USERNAME=test
>       - DOKUWIKI_PASSWORD=tesa
>       - DOKUWIKI_WIKI_NAME=daking
>     labels:
>       - traefik.enable=true
>       - "traefik.frontend.rule=Host:doku.localhost"
> 
> networks:
>   srv:
>     external: true

inside the dokuwiki/dokuwiki folder I replaced te conf, data and lib folders with the folders that I've gotten from the /home/janic/Docker/Local-dev/backup/dokuwiki/dokuwiki/dokuwiki/dw-backup-20190901-190547.tar.bz2 that the backup plugin produced.

lib/images/smileys/local
this file seems to be empty?

**Comment by thepenguinthatwants** [comment]
Actually I compared now that local file to the normal one.. seems like it should be a folder.
When I deleted that and created a folder.

Tried to docker-compose up again.

```
Attaching to dokuwiki_dokuwiki_1
dokuwiki_1  | 
dokuwiki_1  | Welcome to the Bitnami dokuwiki container
dokuwiki_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
dokuwiki_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
dokuwiki_1  | 
dokuwiki_1  | nami    INFO  Initializing apache
dokuwiki_1  | nami    INFO  apache successfully initialized
dokuwiki_1  | nami    INFO  Initializing php
dokuwiki_1  | nami    INFO  php successfully initialized
dokuwiki_1  | nami    INFO  Initializing dokuwiki
dokuwiki_1  | Error executing 'postInstallation': ELOOP: too many symbolic links encountered, stat '/bitnami/dokuwiki/lib/images/interwiki'
```

**Comment by thepenguinthatwants** [comment]
I guess the problem is with the behaviour of backup plugin.. not about this image.

**Comment by alemorcuq** [comment]
Hi, @thepenguinthatwants.

I've been able to restore a backup generated with the plugin you mentioned. I made the backup enabling all options. To restore it:

First, I extracted the back to a `wiki` directory (you can use the directory you want)

```bash
$ mkdir -p wiki
$ tar -xf my-backup.tar.bz2 -C wiki
```

Then, I created I made sure some directories the container expect exist under the `wiki` directory:

```bash
$ mkdir -p wiki/{data,data/cache,data/index,data/locks,data/tmp,conf,lib/plugins,lib/tpl,lib/images/smileys/local,lib/images/interwiki}
```

Finally, I created a file to let the container know that the volume has already been initialized and the data can be restored:

```bash
$ touch wiki/.initialized
```

With all set, I mounted my `wiki` directory that contains the data to the `/bitnami/dokuwiki` directory of the container using my `docker-compose.yaml`:

```yaml
version: '2'
services:
  dokuwiki:
    image: 'bitnami/dokuwiki:0'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './wiki:/bitnami/dokuwiki'
```

And running `docker-compose up` should detect the data and restore it:

```
$ docker-compose up
Creating network "dokuwiki_default" with the default driver
Creating dokuwiki_dokuwiki_1 ... done
Attaching to dokuwiki_dokuwiki_1
dokuwiki_1  |
dokuwiki_1  | Welcome to the Bitnami dokuwiki container
dokuwiki_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
dokuwiki_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
dokuwiki_1  |
dokuwiki_1  | nami    INFO  Initializing apache
dokuwiki_1  | nami    INFO  apache successfully initialized
dokuwiki_1  | nami    INFO  Initializing php
dokuwiki_1  | nami    INFO  php successfully initialized
dokuwiki_1  | nami    INFO  Initializing dokuwiki
dokuwiki_1  | dokuwik INFO
dokuwiki_1  | dokuwik INFO  ########################################################################
dokuwiki_1  | dokuwik INFO   Installation parameters for dokuwiki:
dokuwiki_1  | dokuwik INFO     Persisted data and properties have been restored.
dokuwiki_1  | dokuwik INFO     Any input specified will not take effect.
dokuwiki_1  | dokuwik INFO   This installation requires no credentials.
dokuwiki_1  | dokuwik INFO  ########################################################################
dokuwiki_1  | dokuwik INFO
dokuwiki_1  | nami    INFO  dokuwiki successfully initialized
dokuwiki_1  | INFO  ==> Starting dokuwiki...
dokuwiki_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.21.0.2. Set the 'ServerName' directive globally to suppress this message
dokuwiki_1  | [Wed Sep 04 11:30:38.676203 2019] [ssl:warn] [pid 72] AH01909: 172.21.0.2:443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1  | [Wed Sep 04 11:30:38.676563 2019] [ssl:warn] [pid 72] AH01909: 172.21.0.2:443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.21.0.2. Set the 'ServerName' directive globally to suppress this message
dokuwiki_1  | [Wed Sep 04 11:30:38.710348 2019] [ssl:warn] [pid 72] AH01909: 172.21.0.2:443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1  | [Wed Sep 04 11:30:38.710679 2019] [ssl:warn] [pid 72] AH01909: 172.21.0.2:443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1  | [Wed Sep 04 11:30:38.726377 2019] [mpm_prefork:notice] [pid 72] AH00163: Apache/2.4.41 (Unix) OpenSSL/1.1.0k PHP/7.3.9 configured -- resuming normal operations
dokuwiki_1  | [Wed Sep 04 11:30:38.726417 2019] [core:notice] [pid 72] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```

Try it and let me know how it goes.

Regards,
Alejandro

**Comment by thepenguinthatwants** [comment]
Strangely I get this.


dokuwiki_1  | dokuwik INFO  ########################################################################
dokuwiki_1  | dokuwik INFO   Installation parameters for dokuwiki:
dokuwiki_1  | dokuwik INFO     username: anonymous
dokuwiki_1  | dokuwik INFO     user fullname: Full Name
dokuwiki_1  | dokuwik INFO     Password: **********
dokuwiki_1  | dokuwik INFO     Email: anonymous@example.com
dokuwiki_1  | dokuwik INFO     Wiki Name: anonymous
dokuwiki_1  | dokuwik INFO   (Passwords are not shown for security reasons)
dokuwiki_1  | dokuwik INFO  ########################################################################

**Comment by thepenguinthatwants** [comment]
When I tried the same again I get the

dokuwiki_1  | nami    INFO  Initializing dokuwiki
dokuwiki_1  | dokuwik INFO  Passing wizard, please be patient
dokuwiki_1  | dokuwik INFO 
dokuwiki_1  | dokuwik INFO  ########################################################################
dokuwiki_1  | dokuwik INFO   Installation parameters for dokuwiki:
dokuwiki_1  | dokuwik INFO     username: superuser
dokuwiki_1  | dokuwik INFO     user fullname: Full Name
dokuwiki_1  | dokuwik INFO     Password: **********
dokuwiki_1  | dokuwik INFO     Email: user@example.com
dokuwiki_1  | dokuwik INFO     Wiki Name: Bitnami DokuWiki
dokuwiki_1  | dokuwik INFO   (Passwords are not shown for security reasons)
dokuwiki_1  | dokuwik INFO  ########################################################################

and my dokuwiki is the "This topic does not exist yet" page.

**Comment by thepenguinthatwants** [comment]
But then basic tar the whole package from the server and untar to the local location.. everything worked. So I guess its still okay ^_^

**Comment by alemorcuq** [comment]
Hi, @thepenguinthatwants.

Is this working for you in the end? From your last message I understand you got it working. In that case, I'm very happy you were able to solve your issue. If something is still not working, please tell me and I will continue helping you.

Regards,
Alejandro

**Comment by thepenguinthatwants** [comment]
Hi!

Yeah its working.

**Comment by thepenguinthatwants** [comment]
Thanks ^_^

**Comment by alemorcuq** [comment]
Glad it worked, @thepenguinthatwants! I'm closing this ticket, feel free to open a new one if you find any other issue.
