### ISSUE TITLE
Dokuwiki migration

### ISSUE THREAD

**Issue by simo735** [bitnami/bitnami-docker-dokuwiki#68]
Hello,
Is there a way to transfer articles from a classic dokuwik to this version, in the classic dokuwiki the article are based in: /dokuwiki/data/pages

**Comment by marcosbc** [comment]
Hi @simo735, in principle it should be enough to follow the steps below:

* Launch and initialize the Dokuwiki container persisting the `/bitnami/dokuwiki` directory
* Migrate the following directories from the classic Bitnami Dokuwiki solution, and include them inside the Bitnami Dokuwiki container in the new path:

 * Classic installation path `/opt/bitnami/apps/dokuwiki/htdocs/data` -> To container path `/bitnami/dokuwiki/data`
 * Classic installation path `/opt/bitnami/apps/dokuwiki/htdocs/conf` -> To container path `/bitnami/dokuwiki/conf`

To copy the files from a classic installation to the container, it is easiest if you are able to mount the Dokuwiki persistent volume to a file system, and then upload the files via FTP/SFTP/SCP (or just copy the files if running on the same instance).
