### ISSUE TITLE
Apache logs written to disk inside container

### ISSUE THREAD

**Issue by jojoob** [bitnami/bitnami-docker-dokuwiki#71]
**Description**

The current Docker image saves apache logs to /opt/bitnami/apache/logs/. This is problematic due to missing log rotation. The size of the logs will grow very large over time.
In a previous image version the access_log and error_log in this directory where just symlinks to /dev/stdout and /dev/stderr.

**Steps to reproduce the issue:**

```
## Start a bitnami dokuwiki container (tested with the the image version with digest b891ffe956cf)
$ docker run -d --rm --name dokuwiki-test bitnami/dokuwiki:latest

## Verify the existence and size of the logs
$ docker exec dokuwiki-test ls -l /opt/bitnami/apache/logs/
total 4
-rw-r--r-- 1 root root   0 Mar 26 17:14 access_log
-rw-r--r-- 1 root root 920 Mar 26 17:14 error_log
```

**Describe the results you expected:**

In an older image version (e.g. image with digest d1ba205a5ed0) this looks like:

```bash
$ docker exec dokuwiki-test ls -l /opt/bitnami/apache/logs/
total 0
lrwxrwxrwx 1 root root 11 Jun 24  2019 access_log -> /dev/stdout
lrwxrwxrwx 1 root root 11 Jun 24  2019 error_log -> /dev/stderr
```

**Comment by juan131** [comment]
Hi @jojoob 

Thanks so much for reporting this issue!!

I've done some investigation and it seemed this regression was introduce on this commit: https://github.com/bitnami/bitnami-docker-dokuwiki/commit/b359b7e818863ca61581da17230da4a10df4a752

It seems this is a mistake we introduced while doing a major refactor of how the Apache nami module works. We really appreciate you reported it.

We fixed the issue in our pipeline and, during the weekend, all the Bitnami images including the Apache nami module will be released including it.

We'll notify you as soon as the new Dokuwiki image recovering the symlink to redirect the logs to stdout/stderr is released.

**Comment by juan131** [comment]
Hi @jojoob 

The new Dokuwiki image fixing this issue was released. As you can check in the commands below, it contains the links to redirect the logs to stdout/stderr:

```console
# Download latest image
$ docker pull bitnami/dokuwiki
Using default tag: latest
latest: Pulling from bitnami/dokuwiki
(...)
Status: Downloaded newer image for bitnami/dokuwiki:latest
# Run Dokuwiki and wait unti it's initialized
$ docker run --rm -dit --name doku bitnami/dokuwiki
$ docker logs -f doku
(..)
nami    INFO  dokuwiki successfully initialized
INFO  ==> Starting dokuwiki...
(...)
# Check links
$ docker exec doku ls -la /opt/bitnami/apache/logs
total 8
drwxr-xr-x 1 root root 4096 Mar 28 09:48 .
drwxr-xr-x 1 root root 4096 Mar 28 09:48 ..
lrwxrwxrwx 1 root root   11 Mar 28 09:48 access_log -> /dev/stdout
lrwxrwxrwx 1 root root   11 Mar 28 09:48 error_log -> /dev/stderr
```

**Comment by jojoob** [comment]
Thank you very much for informing me about the release @juan131 !
