### ISSUE TITLE
Host volume mapping of /bitnami folder of container only has the directories data, conf and lib

### ISSUE THREAD

**Issue by varun-kmr** [bitnami/bitnami-docker-dokuwiki#72]
**Description**

Host volume mapping of `/bitnami` folder of container only has the directories `data`, `conf` and `lib`. Other folders are not visible and result in plugin failure.

docker-compose.yml contents

```
version: '2'
services:
  dokuwiki:
    image: 'bitnami/dokuwiki:0'
    ports:
      - '4080:80'
      - '4443:443'
    volumes:
      - 'dokuwiki_data:/bitnami'
volumes:
  dokuwiki_data:
    driver: local
```

**Steps to reproduce the issue:**

1.  Run `docker pull bitnami/dokuwiki`
2.  Create docker-compose.yml file as mentioned on `https://github.com/bitnami/bitnami-docker-dokuwiki/blob/master/0/debian-10/docker-compose.yml`
3.  Run `docker-compose up` (not detached to see logs) in the same directory as `docker-compose.yml`
4.  Login to dokuwiki using default credentials.
5.  Browse to admin and install plugin `icons plugin` either using search and install or manually from `https://www.dokuwiki.org/plugin:icons`
6.  Edit the start page, click on new button by icons plugin. The button has dokuwiki logo.
7.  A new window pops up for the plugin and shows 500 internal server error.
8   Terminal shows the error `PHP Warning:  require_once(/bitnami/dokuwiki/lib/plugins/icons/exe/../../../../inc/init.php): failed to open stream: No such file or directory in /bitnami/dokuwiki/lib/plugins/icons/exe/popup.php on line 17, referer: http://localhost:4080/doku.php?id=start&do=edit`
9.  On terminal, browse to docker volumes location `/var/lib/docker/volumes`
10.  Browse to the `dokuwiki_data` volume and then to `_data/dokuwiki`
11.  As this location on host maps to `/opt/bitnami/dokuwiki` on container (Based on my understanding). 
12.  It should have all files and directories, but only has data, conf and lib directories on host.

**Describe the results you received:**

Terminal shows the error `PHP Warning:  require_once(/bitnami/dokuwiki/lib/plugins/icons/exe/../../../../inc/init.php): failed to open stream: No such file or directory in /bitnami/dokuwiki/lib/plugins/icons/exe/popup.php on line 17, referer: http://localhost:4080/doku.php?id=start&do=edit`

Cause seems to be lack of all files and directories of container path `/opt/bitnami/dokuwiki` on host volume

**Describe the results you expected:**

All files and directories of container path `/opt/bitnami/dokuwiki` be available on host volume `/var/lib/docker/volumes/<VOLUME_NAME>/_data/dokuwiki` instead of data, conf and lib directories only.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.8-ce
 API version:       1.40
 Go version:        go1.14.1
 Git commit:        afacb8b7f0
 Built:             Thu Apr  2 00:04:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.1
  Git commit:       afacb8b7f0
  Built:            Thu Apr  2 00:04:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.4.m
  GitCommit:        d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 12
  Running: 3
  Paused: 0
  Stopped: 9
 Images: 31
 Server Version: 19.03.8-ce
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.6.8-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.896GiB
 Name: vps296006.vps.ovh.ca
 ID: FW3K:BJRM:FIQZ:GVJG:CU7F:3AD5:W4PK:4KWK:LHN5:GMUI:LJEU:MT6L
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build unknown
docker-py version: 4.2.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
VPS on `Linux vps296006.vps.ovh.ca 5.6.8-arch1-1 #1 SMP PREEMPT Wed, 29 Apr 2020 16:22:56 +0000 x86_64 GNU/Linux`

**Comment by miguelaeh** [comment]
Hi @varun-kmr ,
Did you test if this is happening with more plugins or only with the `icons plugin`?

**Comment by varun-kmr** [comment]
Hi @miguelaeh ,
Based on the plugins I use, only this one refers to `inc` folder

**Comment by erik-alm** [comment]
Most DokuWiki plugins will break if they have to create a path to the DOKU_INC (/inc) folder.

The majority of plugins will just `die()` if the variable is missing:

`if(!defined('DOKU_INC')) die();`

But then there's the are cases where the variable is apparently not defined but needed, and it is handled with variants of constructs like this one:

`if (!defined('DOKU_INC')) define('DOKU_INC', realpath(dirname(__FILE__).'/../../../').'/');`

This will, when performed from the `/bitnami/dokuwiki/` folder, of course, en up in `/bitnami/dokuwiki/inc/` and then fail when trying to include things.

The plugins I have with these problems are:

- definitionlist
- discussion
- gallery
- orphanswanted
- searchindex
- styling

I have a total of 26 plugins, so this means about 25% of my plugins are broken.

It's not just one plugin.

A fix would be to include the "inc" folder in the mapping, but that's just a fix if other folders aren't needed as well. I haven't given DokuWiki in a docker image more serious testing than this yet...

The current assumptions about how things work seem a bit untested...

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-dokuwiki#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
