### ISSUE TITLE
Feature request: Set upload-size

### ISSUE THREAD

**Issue by runar-indico** [bitnami/bitnami-docker-dokuwiki#73]
Hi, We would like to change the upload-size. I see this is supported using https://www.dokuwiki.org/faq:uploadsize

It would be great if this could be changed with an environment-variable, as I think it is a very common setting.

Also, I was unable to find any of the files mentioned in the aforementioned link within the container, so I do not know really where to mount a custom file to set that setting manually.

**Comment by dani8art** [comment]
Hi @runar-indico you can find `php.in` in `/opt/bitnami/php/conf/php.ini` please give a try updating these values on the file.

**Comment by marcosbc** [comment]
Hi @runar-indico, since `20180422.4.0-debian-10-r0` you can use the `PHP_UPLOAD_MAX_FILESIZE` environment variable which for this purpose. 

Best regards

**Comment by runar-indico** [comment]
Great, thank you.
