### ISSUE TITLE
Update to "Hogfather" version

### ISSUE THREAD

**Issue by Elkiscoming** [bitnami/bitnami-docker-dokuwiki#74]
Do you plan to release an image with "Hogfather" DokuWiki version?

**Comment by beltran-rubo** [comment]
Hi @Elkiscoming 

Thanks for the suggestion. We usually release the stable versions for the applications. I see this is a release candidate so we will add it to the catalog once it is considered stable.

**Comment by Elkiscoming** [comment]
Yes, you're right. Thanks for your response.

**Comment by rafariossaa** [comment]
Hi,
  You are welcome

**Comment by MrReSc** [comment]
Hogfather has now been officially released.  See https://www.dokuwiki.org/changes

**Comment by miguelaeh** [comment]
Hi @MrReSc ,
Thank you for the notification.
I checked it and our system has already detected the new version. We will work to release it as soon as possible.
Regards.

**Comment by tasism** [comment]
Any updates on this please? Release seems still to be 2018-04-22c "Greebo". Thank you for sharing some news if possible.

**Comment by miguelaeh** [comment]
Hi @tasism ,
 How are you checking the version? Are you using the tag `20200729.0.0-debian-10-r39` ?

**Comment by tasism** [comment]
> Hi @tasism ,
> How are you checking the version? Are you using the tag `20200729.0.0-debian-10-r39` ?

I am doing a `docker pull bitnami/dokuwiki:latest` and a `docker-compose up -d --build` at regular intervals to rebuild the container (based on a docker-compose file).

The image I use is:
`FROM 'docker.io/bitnami/dokuwiki:0-debian-10'`

**Comment by miguelaeh** [comment]
Hi @tasism ,
The image you are using is from two months ago, check the following:
```
bitnami/dokuwiki                                             latest                                                             4a8652f2f04b        10 hours ago        704MB
bitnami/dokuwiki                                             0-debian-10                                                        5e9257066d95        2 months ago        703MB
```
