### ISSUE TITLE
Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80

### ISSUE THREAD

**Issue by aliceinwire** [bitnami/bitnami-docker-dokuwiki#75]
Attaching to dokuwiki
dokuwiki                 | dokuwiki 08:57:28.94 
dokuwiki                 | dokuwiki 08:57:28.95 Welcome to the Bitnami dokuwiki container
dokuwiki                 | dokuwiki 08:57:28.95 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
dokuwiki                 | dokuwiki 08:57:28.95 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
dokuwiki                 | dokuwiki 08:57:28.95 
dokuwiki                 | dokuwiki 08:57:28.95 INFO  ==> ** Starting DokuWiki setup **
dokuwiki                 | dokuwiki 08:57:28.99 WARN  ==> The directory '/bitnami/apache/conf' was externally mounted. This is a legacy configuration and will be deprecated soon. Please mount certificate files at '/opt/bitnami/apache/conf' instead. Find an example at: https://github.com/bitnami/bitnami-docker-apache#full-configuration
dokuwiki                 | dokuwiki 08:57:28.99 WARN  ==> Restoring configuration at '/bitnami/apache/conf' to '/opt/bitnami/apache/conf'
dokuwiki                 | dokuwiki 08:57:29.00 INFO  ==> Configuring PHP options
dokuwiki                 | dokuwiki 08:57:29.04 WARN  ==> The dokuwiki virtual host file '/opt/bitnami/apache/conf/vhosts/dokuwiki-vhost.conf' is not writable. Configurations based on environment variables will not be applied for this file.
dokuwiki                 | dokuwiki 08:57:29.04 WARN  ==> The dokuwiki virtual host file '/opt/bitnami/apache/conf/vhosts/dokuwiki-https-vhost.conf' is not writable. Configurations based on environment variables will not be applied for this file.
dokuwiki                 | dokuwiki 08:57:29.05 INFO  ==> Restoring persisted DokuWiki installation
dokuwiki                 | dokuwiki 08:57:29.22 INFO  ==> ** DokuWiki setup finished! **
dokuwiki                 | 
dokuwiki                 | dokuwiki 08:57:29.23 INFO  ==> ** Starting Apache **
dokuwiki                 | (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
dokuwiki                 | no listening sockets available, shutting down
dokuwiki                 | AH00015: Unable to open logs

**Comment by Drudoo** [comment]
just updated my container and got this error too...

**Comment by javsalgar** [comment]
Hi,

Starting from this container version (https://github.com/bitnami/bitnami-docker-dokuwiki#020180422202005011246-debian-10-r68), the container was moved to non-root. In this case, moving from a root container to a non-root container may not work out of the box. Could you modify your docker-compose.yaml file and set `user:root` in the dokuwiki container? Could you confirm that it works?

**Comment by tuxpeople** [comment]
Thanks for breaking my stuff with changing the ports... :-P

**Comment by Drudoo** [comment]
@javsalgar that did not fix the issue. I moved to linuxserver image instead and that worked.

**Comment by javsalgar** [comment]
Sorry to hear that, did you get the exact error when setting `user: root`, it should be able to bind port 80.

**Comment by jueves** [comment]
Hi,
I also got this problem when upgrading to the new versions, and it does change when I use `user: root`, but it keeps restarting every 10 seconds or so.

It works perfect with `bitnami/dokuwiki:0.20180422.202005011246-debian-10-r67`.

It seems like a problem related to `/opt/bitnami/apache/conf/httpd.conf`

Here are the logs for each of the three configurations.

#### Last image without `user: root`

    dokuwiki 09:40:58.65 
    dokuwiki 09:40:58.65 Welcome to the Bitnami dokuwiki container
    dokuwiki 09:40:58.66 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
    dokuwiki 09:40:58.66 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
    dokuwiki 09:40:58.66 
    dokuwiki 09:40:58.67 INFO  ==> ** Starting DokuWiki setup **
    dokuwiki 09:40:58.70 WARN  ==> The directory '/bitnami/apache/conf' was externally mounted. This is a legacy configuration and will be deprecated soon. Please mount certificate files at '/opt/bitnami/apache/conf' instead. Find an example at: https://github.com/bitnami/bitnami-docker-apache#full-configuration
    dokuwiki 09:40:58.70 WARN  ==> Restoring configuration at '/bitnami/apache/conf' to '/opt/bitnami/apache/conf'
    dokuwiki 09:40:58.73 INFO  ==> Configuring PHP options
    dokuwiki 09:40:58.80 WARN  ==> The dokuwiki virtual host file '/opt/bitnami/apache/conf/vhosts/dokuwiki-vhost.conf' is not writable. Configurations based on environment variables will not be applied for this file.
    dokuwiki 09:40:58.80 WARN  ==> The dokuwiki virtual host file '/opt/bitnami/apache/conf/vhosts/dokuwiki-https-vhost.conf' is not writable. Configurations based on environment variables will not be applied for this file.
    dokuwiki 09:40:58.81 INFO  ==> Restoring persisted DokuWiki installation
    dokuwiki 09:40:59.30 INFO  ==> ** DokuWiki setup finished! **
    
    dokuwiki 09:40:59.31 INFO  ==> ** Starting Apache **
    (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
    no listening sockets available, shutting down
    AH00015: Unable to open logs`

#### Last image with `user: root`

    dokuwiki 09:44:10.88 
    dokuwiki 09:44:10.88 Welcome to the Bitnami dokuwiki container
    dokuwiki 09:44:10.88 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
    dokuwiki 09:44:10.88 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
    dokuwiki 09:44:10.89 
    dokuwiki 09:44:10.89 INFO  ==> ** Starting DokuWiki setup **
    dokuwiki 09:44:10.95 WARN  ==> The directory '/bitnami/apache/conf' was externally mounted. This is a legacy configuration and will be deprecated soon. Please mount certificate files at '/opt/bitnami/apache/conf' instead. Find an example at: https://github.com/bitnami/bitnami-docker-apache#full-configuration
    dokuwiki 09:44:10.95 WARN  ==> Restoring configuration at '/bitnami/apache/conf' to '/opt/bitnami/apache/conf'
    dokuwiki 09:44:11.01 INFO  ==> Configuring PHP options
    dokuwiki 09:44:11.11 INFO  ==> Restoring persisted DokuWiki installation
    dokuwiki 09:44:11.59 INFO  ==> ** DokuWiki setup finished! **

    dokuwiki 09:44:11.61 INFO  ==> ** Starting Apache **
    [Mon Jul 27 09:44:11.717512 2020] [ssl:warn] [pid 1] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
    [Mon Jul 27 09:44:11.718249 2020] [ssl:warn] [pid 1] AH01909: localhost:8443:0 server certificate does NOT include an ID which matches the server name
    [Mon Jul 27 09:44:11.784775 2020] [ssl:warn] [pid 1] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
    [Mon Jul 27 09:44:11.785390 2020] [ssl:warn] [pid 1] AH01909: localhost:8443:0 server certificate does NOT include an ID which matches the server name
    [Mon Jul 27 09:44:11.806044 2020] [core:error] [pid 1] (2)No such file or directory: AH00099: could not create /opt/bitnami/apache/tmp/httpd.pid
    [Mon Jul 27 09:44:11.806094 2020] [core:error] [pid 1] AH00100: httpd: could not log pid to file /opt/bitnami/apache/tmp/httpd.pid

#### Working image without `user: root`

    Welcome to the Bitnami dokuwiki container
    Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
    Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
    
    nami    INFO  Initializing php
    php     WARN  The directory '/bitnami/php/conf' was externally mounted. This is a legacy configuration and will be deprecated soon. Please mount configuration files at '/opt/bitnami/php/conf' instead.
    php     WARN  Restoring configuration at '/bitnami/php/conf' to '/opt/bitnami/php/conf'...
    nami    INFO  php successfully initialized
    nami    INFO  Initializing apache
    apache  WARN  The directory '/bitnami/apache/conf' was externally mounted. This is a legacy configuration and will be deprecated soon. Please mount configuration files at '/opt/bitnami/apache/conf' instead. Find an example at: https://github.com/bitnami/bitnami-docker-apache#full-configuration
    apache  WARN  Restoring configuration at '/bitnami/apache/conf' to '/opt/bitnami/apache/conf'...
    nami    INFO  apache successfully initialized
    nami    INFO  Initializing dokuwiki
    dokuwik INFO  Preparing PHP environment...
    dokuwik INFO 
    dokuwik INFO  ########################################################################
    dokuwik INFO   Installation parameters for dokuwiki:
    dokuwik INFO     Persisted data and properties have been restored.
    dokuwik INFO     Any input specified will not take effect.
    dokuwik INFO   This installation requires no credentials.
    dokuwik INFO  ########################################################################
    dokuwik INFO 
    nami    INFO  dokuwiki successfully initialized
    INFO  ==> Starting dokuwiki... 
    [Mon Jul 27 09:56:43.183342 2020] [ssl:warn] [pid 64] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
    [Mon Jul 27 09:56:43.189422 2020] [ssl:warn] [pid 64] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
    [Mon Jul 27 09:56:43.291754 2020] [ssl:warn] [pid 64] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
    [Mon Jul 27 09:56:43.292715 2020] [ssl:warn] [pid 64] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
    [Mon Jul 27 09:56:43.320223 2020] [mpm_prefork:notice] [pid 64] AH00163: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.3.19 configured -- resuming normal operations
    [Mon Jul 27 09:56:43.320569 2020] [core:notice] [pid 64] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'

**Comment by javsalgar** [comment]
Hi,

I've been unable to reproduce the issue:

Installed version `bitnami/dokuwiki:0.20180422.202005011246-debian-10-r62`


```
dokuwiki_1  |
dokuwiki_1  | Welcome to the Bitnami dokuwiki container
dokuwiki_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
dokuwiki_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
dokuwiki_1  |
dokuwiki_1  | nami    INFO  Initializing php
dokuwiki_1  | nami    INFO  php successfully initialized
dokuwiki_1  | nami    INFO  Initializing apache
dokuwiki_1  | nami    INFO  apache successfully initialized
dokuwiki_1  | nami    INFO  Initializing dokuwiki
dokuwiki_1  | dokuwik INFO  Preparing PHP environment...
dokuwiki_1  | dokuwik INFO  Passing wizard, please be patient
dokuwiki_1  | dokuwik INFO
dokuwiki_1  | dokuwik INFO  ########################################################################
dokuwiki_1  | dokuwik INFO   Installation parameters for dokuwiki:
dokuwiki_1  | dokuwik INFO     username: superuser
dokuwiki_1  | dokuwik INFO     user fullname: Full Name
dokuwiki_1  | dokuwik INFO     Password: **********
dokuwiki_1  | dokuwik INFO     Email: user@example.com
dokuwiki_1  | dokuwik INFO     Wiki Name: Bitnami DokuWiki
dokuwiki_1  | dokuwik INFO   (Passwords are not shown for security reasons)
dokuwiki_1  | dokuwik INFO  ########################################################################
dokuwiki_1  | dokuwik INFO
dokuwiki_1  | nami    INFO  dokuwiki successfully initialized
dokuwiki_1  | INFO  ==> Starting dokuwiki...
dokuwiki_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
dokuwiki_1  | [Tue Jul 28 08:27:47.024062 2020] [ssl:warn] [pid 76] AH01909: 172.18.0.2:443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1  | [Tue Jul 28 08:27:47.024412 2020] [ssl:warn] [pid 76] AH01909: 172.18.0.2:443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
dokuwiki_1  | [Tue Jul 28 08:27:47.050774 2020] [ssl:warn] [pid 76] AH01909: 172.18.0.2:443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1  | [Tue Jul 28 08:27:47.051082 2020] [ssl:warn] [pid 76] AH01909: 172.18.0.2:443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1  | [Tue Jul 28 08:27:47.062783 2020] [mpm_prefork:notice] [pid 76] AH00163: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.3.19 configured -- resuming normal operations
dokuwiki_1  | [Tue Jul 28 08:27:47.062838 2020] [core:notice] [pid 76] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```

Then I changed to the most recent and set `user:root`. `bitnami/dokuwiki:0`

```
dokuwiki_1  | dokuwiki 08:35:06.53 Welcome to the Bitnami dokuwiki container
dokuwiki_1  | dokuwiki 08:35:06.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
dokuwiki_1  | dokuwiki 08:35:06.53 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
dokuwiki_1  | dokuwiki 08:35:06.53
dokuwiki_1  | dokuwiki 08:35:06.53 INFO  ==> ** Starting DokuWiki setup **
dokuwiki_1  | dokuwiki 08:35:06.58 INFO  ==> Configuring PHP options
dokuwiki_1  | dokuwiki 08:35:06.62 INFO  ==> Restoring persisted DokuWiki installation
dokuwiki_1  | dokuwiki 08:35:06.82 INFO  ==> ** DokuWiki setup finished! **
dokuwiki_1  |
dokuwiki_1  | dokuwiki 08:35:06.83 INFO  ==> ** Starting Apache **
dokuwiki_1  | [Tue Jul 28 08:35:06.863882 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1  | [Tue Jul 28 08:35:06.864734 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1  | [Tue Jul 28 08:35:06.889272 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1  | [Tue Jul 28 08:35:06.889611 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1  | [Tue Jul 28 08:35:06.901052 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.3.20 configured -- resuming normal operations
dokuwiki_1  | [Tue Jul 28 08:35:06.901122 2020] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'

```

I'm not sure why the error with the pid. Could you try executing docker-compose run dokuwiki bash and check the permissions in the tmp folder?

**Comment by fri-sch** [comment]
I'm seeing the exact same problem when upgrading to the latest 20180422 version.

@javsalgar For me it looks like this (with `user: root`):

```
docker-compose run dokuwiki /bin/bash

root@348c8cbe1624:/# ls /opt/bitnami/apache/tmp               
ls: cannot access '/opt/bitnami/apache/tmp': No such file or directory

root@348c8cbe1624:/# ls -l /opt/bitnami/apache/   
total 68
drwxr-xr-x  2 root root  4096 Jun 25 15:43 bin
drwxr-xr-x  2 root root  4096 Jun 25 15:43 build
drwxr-xr-x  2 root root  4096 Jun 25 15:43 build-1
drwxr-xr-x  2 root root  4096 Jun 25 15:43 cgi-bin
drwxrwxr-x  1 root root  4096 Jul 28 17:34 conf
drwxr-xr-x  3 root root  4096 Jun 25 15:43 error
drwxrwxr-x  1 root root  4096 Jun 25 15:43 htdocs
drwxr-xr-x  3 root root  4096 Jun 25 15:43 icons
drwxr-xr-x  3 root root  4096 Jun 25 15:43 include
drwxr-xr-x  4 root root  4096 Jun 25 15:43 lib
drwxr-xr-x  2 root root  4096 Jun 25 15:43 licenses
drwxrwxr-x  1 root root  4096 Jul 28 17:35 logs
drwxr-xr-x 14 root root 12288 Jun 25 15:43 manual
drwxr-xr-x  1 root root  4096 Jul 13 07:34 modules
drwxr-xr-x  1 root root  4096 Jul 28 17:35 var

root@348c8cbe1624:/# /opt/bitnami/scripts/dokuwiki/entrypoint.sh /opt/bitnami/scripts/dokuwiki/run.sh
dokuwiki 18:31:13.22 
dokuwiki 18:31:13.22 Welcome to the Bitnami dokuwiki container
dokuwiki 18:31:13.23 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
dokuwiki 18:31:13.23 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
dokuwiki 18:31:13.23 

/opt/bitnami/scripts/dokuwiki/entrypoint.sh: line 30: /opt/bitnami/scripts/dokuwiki/run.sh: No such file or directory

root@348c8cbe1624:/# /opt/bitnami/scripts/dokuwiki/entrypoint.sh /opt/bitnami/scripts/apache/run.sh
dokuwiki 18:31:44.43 
dokuwiki 18:31:44.43 Welcome to the Bitnami dokuwiki container
dokuwiki 18:31:44.43 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
dokuwiki 18:31:44.43 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
dokuwiki 18:31:44.43 
dokuwiki 18:31:44.43 INFO  ==> ** Starting DokuWiki setup **
dokuwiki 18:31:44.46 WARN  ==> The directory '/bitnami/apache/conf' was externally mounted. This is a legacy configuration and will be deprecated soon. Please mount certificate files at '/opt/bitnami/apache/conf' instead. Find an example at: https://github.com/bitnami/bitnami-docker-apache#full-configuration
dokuwiki 18:31:44.46 WARN  ==> Restoring configuration at '/bitnami/apache/conf' to '/opt/bitnami/apache/conf'
dokuwiki 18:31:44.49 INFO  ==> Configuring PHP options
dokuwiki 18:31:44.53 INFO  ==> Restoring persisted DokuWiki installation
dokuwiki 18:31:44.69 INFO  ==> ** DokuWiki setup finished! **

dokuwiki 18:31:44.69 INFO  ==> ** Starting Apache **
[Wed Jul 29 18:31:44.822832 2020] [ssl:warn] [pid 24] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jul 29 18:31:44.823129 2020] [ssl:warn] [pid 24] AH01909: localhost:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Jul 29 18:31:44.847732 2020] [ssl:warn] [pid 24] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jul 29 18:31:44.847970 2020] [ssl:warn] [pid 24] AH01909: localhost:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Jul 29 18:31:44.889287 2020] [core:error] [pid 24] (2)No such file or directory: AH00099: could not create /opt/bitnami/apache/tmp/httpd.pid
[Wed Jul 29 18:31:44.889318 2020] [core:error] [pid 24] AH00100: httpd: could not log pid to file /opt/bitnami/apache/tmp/httpd.pid
```

**Comment by javsalgar** [comment]
Hi,

And after that, could you see if the tmp folder is created? If not, could you try to manually create it and see if that fixes the issue?

**Comment by fri-sch** [comment]
> Hi,
> 
> And after that, could you see if the tmp folder is created? If not, could you try to manually create it and see if that fixes the issue?

Yes, it seems like creating the temp directory fixes it temporarily:

```
root@276b94058e7f:/# mkdir /opt/bitnami/apache/tmp
root@276b94058e7f:/# /opt/bitnami/scripts/dokuwiki/entrypoint.sh /opt/bitnami/scripts/apache/run.sh
dokuwiki 09:16:33.00 
dokuwiki 09:16:33.00 Welcome to the Bitnami dokuwiki container
dokuwiki 09:16:33.00 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
dokuwiki 09:16:33.00 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
dokuwiki 09:16:33.01 
dokuwiki 09:16:33.01 INFO  ==> ** Starting DokuWiki setup **
dokuwiki 09:16:33.02 WARN  ==> The directory '/bitnami/apache/conf' was externally mounted. This is a legacy configuration and will be deprecated soon. Please mount certificate files at '/opt/bitnami/apache/conf' instead. Find an example at: https://github.com/bitnami/bitnami-docker-apache#full-configuration
dokuwiki 09:16:33.02 WARN  ==> Restoring configuration at '/bitnami/apache/conf' to '/opt/bitnami/apache/conf'
dokuwiki 09:16:33.04 INFO  ==> Configuring PHP options
dokuwiki 09:16:33.07 INFO  ==> Restoring persisted DokuWiki installation
dokuwiki 09:16:33.10 INFO  ==> ** DokuWiki setup finished! **

dokuwiki 09:16:33.11 INFO  ==> ** Starting Apache **
[Thu Jul 30 09:16:33.161392 2020] [ssl:warn] [pid 111] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 30 09:16:33.161681 2020] [ssl:warn] [pid 111] AH01909: localhost:8443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 30 09:16:33.181841 2020] [ssl:warn] [pid 111] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 30 09:16:33.182078 2020] [ssl:warn] [pid 111] AH01909: localhost:8443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 30 09:16:33.193477 2020] [mpm_prefork:notice] [pid 111] AH00163: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.3.20 configured -- resuming normal operations
[Thu Jul 30 09:16:33.193520 2020] [core:notice] [pid 111] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```

**Comment by javsalgar** [comment]
Does the issue appear if you restart the container now?

**Comment by MrReSc** [comment]
Unfortunately I have the same problem. How do I get my existing installation running?

**Comment by beltran-rubo** [comment]
hi @MrReSc based on https://github.com/bitnami/bitnami-docker-dokuwiki#020180422202005011246-debian-10-r68 you can use a previous image version to continue using the previous "root" approach, e.g. 0.20180422.202005011246-debian-10-r65

**Comment by MrReSc** [comment]
@beltran-rubo Thanks for your answer. Yeah, I know it still works with an old image. But there are plugins that only work with the new release of DokuWiki.

**Comment by fri-sch** [comment]
> Does the issue appear if you restart the container now?

Yes it does. That's the problem.

**Comment by marafa** [comment]
in case a count is needed, i am also affected

**Comment by dani8art** [comment]
Hi all,

I did the same as @javsalgar and I've been unable to reproduce it as well, how are you setting persistence? 

- by using docker volume

```yaml
    volumes:
      - 'dokuwiki_data:/bitnami/dokuwiki'
volumes:
  dokuwiki_data:
    driver: local
```

- by using local mapping

```yaml
    volumes:
      - '/local/path/to/my-data:/bitnami/dokuwiki'
```

**Comment by fri-sch** [comment]
@dani8art I happen to have it like this:

```
volumes:
      - 'dokuwiki-data:/bitnami'

volumes:
  dokuwiki-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_DATA_DIR}/dokuwiki-data
```

**Comment by mrpandat** [comment]
Hey, I updated my container yesterday, and i have the same error since.

**Comment by marafa** [comment]
this is how i run it now

```
podman run -d -p 80:8080 -p 443:8443 --name dokuwiki --restart always -e DOKUWIKI_PASSWORD=$password -e DOKUWIKI_USERNAME=admin -e DOKUWIKI_WIKI_NAME=Dokuwiki --volume /opt/dokuwiki:/bitnami/$image bitnami/$image:latest
```
note the internal port has changed for some reason

**Comment by danukefl** [comment]
I am experiencing the same issue and rolled back to a previous image version. I attempted to edit the existing config files to ports 8080/8443, but then it couldn't create a tmp pid file even if permissions were 777. Using the old Dokuwiki folder in a new install throws class errors so I'm just going to stick with the old one until an upgrade path is available.

**Comment by aliceinwire** [comment]
I tried to upgrade but also the php part have problems.
Solved by backing up the dokuwiki_data and removing the old volume.
Starting dokuwiki with a new volume and copying back only the data folder.
I think this is the fastest way. 
I could also upgrade directly from the old image but in any case I had to rewrite part of the php code.

**Comment by javsalgar** [comment]
Hi,

If you could provide more details about your Host Operating System, the Docker version and the volume technology you are using it would be very helpful to us, as we are struggling to reproduce the issue.

**Comment by dani8art** [comment]
Hi All, I've just tried the following and it works for me. 

Having a docker-compose with the old version `docker-compose.old.yml`, to me:

```yaml
version: '2'
services:
  dokuwiki:
    image: 'docker.io/bitnami/dokuwiki:0.20180422.202005011246-debian-10-r62'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - 'dokuwiki_data:/bitnami/dokuwiki'
volumes:
  dokuwiki_data:
    driver: local
```

It was deployed like

```yaml
$ docker-compose -f docker-compose.old.yml up -d
```

I applied these changes in order to change the volumes and ports

```diff
--- docker-compose.old.yml      2020-08-14 14:20:06.722946928 +0000
+++ docker-compose.new.yml      2020-08-17 11:07:16.106357961 +0000
@@ -1,12 +1,15 @@
 version: '2'
 services:
   dokuwiki:
-    image: 'docker.io/bitnami/dokuwiki:0.20180422.202005011246-debian-10-r62'
+    image: 'docker.io/bitnami/dokuwiki:latest'
     ports:
-      - '8080:80'
-      - '8443:443'
+      - '8080:8080'
+      - '8443:8443'
     volumes:
-      - 'dokuwiki_data:/bitnami/dokuwiki'
+      - 'dokuwiki_data:/bitnami/dokuwiki.old'
+      - 'dokuwiki_data_new:/bitnami/dokuwiki'
 volumes:
   dokuwiki_data:
     driver: local
+  dokuwiki_data_new:
+    driver: local
```

Deploy the new version

```console
$ docker-compose -f docker-compose.new.yml up -d
```

Move your old data to the proper folder 

```
$ docker-compose -f docker-compose.old.yml exec -u 0 dokuwiki mv /bitnami/dokuwiki.old/data /bitnami/dokuwiki
$ docker-compose -f docker-compose.new.yml exec -u 0 dokuwiki chown -R 1001:root /bitnami/dokuwiki/data
```

**Comment by dani8art** [comment]
Hi @fri-sch yes you are right we mixed versions, sorry. 

Anayway, I tested to migrate from `bitnami/dokuwiki:0.20180422.202005011246-debian-10-r67` -> `bitnami/dokuwiki:20180422` using this approach and it worked fine for me

**Diff between versions**
```diff
--- docker-compose.old.yml      2020-09-14 12:59:08.006763829 +0000
+++ docker-compose.new.yml      2020-09-14 12:59:23.854284510 +0000
@@ -1,12 +1,15 @@
 version: '2'
 services:
   dokuwiki:
-    image: 'bitnami/dokuwiki:0.20180422.202005011246-debian-10-r67'
+    image: 'bitnami/dokuwiki:20180422'
     ports:
-      - '8080:80'
-      - '8443:443'
+      - '8080:8080'
+      - '8443:8443'
     volumes:
-      - 'dokuwiki_data:/bitnami/dokuwiki'
+      - 'dokuwiki_data:/bitnami/dokuwiki.old'
+      - 'dokuwiki_data_new:/bitnami/dokuwiki'
 volumes:
   dokuwiki_data:
     driver: local
+  dokuwiki_data_new:
+    driver: local
```

**Upgrade**
```console
$ docker-compose -f docker-compose.old.yml up -d
$ docker-compose -f docker-compose.new.yml up -d
```
**Backup**
```console
$ docker-compose -f docker-compose.new.yml exec -u 0 dokuwiki cp -r /bitnami/dokuwiki.old/data /bitnami/dokuwiki
$ docker-compose -f docker-compose.new.yml exec -u 0 dokuwiki chown -R 1001:root /bitnami/dokuwiki/data
```
