### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by tuxpeople** [bitnami/bitnami-docker-dokuwiki#79]
Currently, my Dokuwiki only dieplays an empty white page.

In the docker logs, I can see this error:

`privat_dokuwiki_1        | [Sat Aug 15 17:50:51.347608 2020] [php7:error] [pid 91] [client 192.168.80.12:44236] PHP Fatal error:  Uncaught Error: Class 'dokuwiki\\plugin\\config\\core\\Setting\\Setting' not found in /opt/bitnami/dokuwiki/inc/deprecated.php:61\nStack trace:\n#0 /opt/bitnami/dokuwiki/inc/load.php(38): require_once()\n#1 /opt/bitnami/dokuwiki/inc/init.php(200): require_once('/opt/bitnami/do...')\n#2 /opt/bitnami/dokuwiki/index.php(18): require_once('/opt/bitnami/do...')\n#3 {main}\n  thrown in /opt/bitnami/dokuwiki/inc/deprecated.php on line 61`

**Comment by rafariossaa** [comment]
Hi,
  Does this happen when performing some action ? Is this a clean install ?
  I have just started a dokuwiki and I am not able to reproduce the issue.

**Comment by tuxpeople** [comment]
Hi

It's happening when trying to access it.

Startup:
<pre>
privat_dokuwiki_1        | dokuwiki 09:24:23.24
privat_dokuwiki_1        | dokuwiki 09:24:23.24 Welcome to the Bitnami dokuwiki container
privat_dokuwiki_1        | dokuwiki 09:24:23.25 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
privat_dokuwiki_1        | dokuwiki 09:24:23.25 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
privat_dokuwiki_1        | dokuwiki 09:24:23.25
privat_dokuwiki_1        | dokuwiki 09:24:23.30 INFO  ==> ** Starting DokuWiki setup **
privat_dokuwiki_1        | dokuwiki 09:24:23.45 INFO  ==> Configuring PHP options
privat_dokuwiki_1        | dokuwiki 09:24:23.71 INFO  ==> Restoring persisted DokuWiki installation
privat_dokuwiki_1        | dokuwiki 09:24:24.55 INFO  ==> ** DokuWiki setup finished! **
privat_dokuwiki_1        |
privat_dokuwiki_1        | dokuwiki 09:24:24.59 INFO  ==> ** Starting Apache **
privat_dokuwiki_1        | [Wed Aug 19 09:24:24.816876 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
privat_dokuwiki_1        | [Wed Aug 19 09:24:24.817713 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
privat_dokuwiki_1        | [Wed Aug 19 09:24:24.862482 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
privat_dokuwiki_1        | [Wed Aug 19 09:24:24.863134 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
privat_dokuwiki_1        | [Wed Aug 19 09:24:24.888066 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.21 configured -- resuming normal operations
privat_dokuwiki_1        | [Wed Aug 19 09:24:24.888166 2020] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
</pre>

When I try to access it, this happens:

<pre>
privat_dokuwiki_1        | [Wed Aug 19 09:24:52.403021 2020] [php7:error] [pid 93] [client 172.19.0.9:37014] PHP Fatal error:  Uncaught Error: Class 'dokuwiki\\plugin\\config\\core\\Setting\\Setting' not found in /opt/bitnami/dokuwiki/inc/deprecated.php:61\nStack trace:\n#0 /opt/bitnami/dokuwiki/inc/load.php(38): require_once()\n#1 /opt/bitnami/dokuwiki/inc/init.php(200): require_once('/opt/bitnami/do...')\n#2 /opt/bitnami/dokuwiki/doku.php(36): require_once('/opt/bitnami/do...')\n#3 {main}\n  thrown in /opt/bitnami/dokuwiki/inc/deprecated.php on line 61
privat_dokuwiki_1        | 172.19.0.9 - - [19/Aug/2020:09:24:52 +0200] "GET / HTTP/1.0" 500 -
privat_dokuwiki_1        | [Wed Aug 19 09:24:52.451884 2020] [php7:error] [pid 92] [client 172.19.0.9:37016] PHP Fatal error:  Uncaught Error: Class 'dokuwiki\\plugin\\config\\core\\Setting\\Setting' not found in /opt/bitnami/dokuwiki/inc/deprecated.php:61\nStack trace:\n#0 /opt/bitnami/dokuwiki/inc/load.php(38): require_once()\n#1 /opt/bitnami/dokuwiki/inc/init.php(200): require_once('/opt/bitnami/do...')\n#2 /opt/bitnami/dokuwiki/doku.php(36): require_once('/opt/bitnami/do...')\n#3 {main}\n  thrown in /opt/bitnami/dokuwiki/inc/deprecated.php on line 61, referer: https://wiki.eighty-three.me/
privat_dokuwiki_1        | 172.19.0.9 - - [19/Aug/2020:09:24:52 +0200] "GET /favicon.ico HTTP/1.0" 500 -
privat_dokuwiki_1        | [Wed Aug 19 09:24:52.528909 2020] [php7:error] [pid 90] [client 172.19.0.9:37020] PHP Fatal error:  Uncaught Error: Class 'dokuwiki\\plugin\\config\\core\\Setting\\Setting' not found in /opt/bitnami/dokuwiki/inc/deprecated.php:61\nStack trace:\n#0 /opt/bitnami/dokuwiki/inc/load.php(38): require_once()\n#1 /opt/bitnami/dokuwiki/inc/init.php(200): require_once('/opt/bitnami/do...')\n#2 /opt/bitnami/dokuwiki/doku.php(36): require_once('/opt/bitnami/do...')\n#3 {main}\n  thrown in /opt/bitnami/dokuwiki/inc/deprecated.php on line 61
privat_dokuwiki_1        | 172.19.0.9 - - [19/Aug/2020:09:24:52 +0200] "GET /apple-touch-icon-precomposed.png HTTP/1.0" 500 -
privat_dokuwiki_1        | [Wed Aug 19 09:24:52.552740 2020] [php7:error] [pid 91] [client 172.19.0.9:37022] PHP Fatal error:  Uncaught Error: Class 'dokuwiki\\plugin\\config\\core\\Setting\\Setting' not found in /opt/bitnami/dokuwiki/inc/deprecated.php:61\nStack trace:\n#0 /opt/bitnami/dokuwiki/inc/load.php(38): require_once()\n#1 /opt/bitnami/dokuwiki/inc/init.php(200): require_once('/opt/bitnami/do...')\n#2 /opt/bitnami/dokuwiki/doku.php(36): require_once('/opt/bitnami/do...')\n#3 {main}\n  thrown in /opt/bitnami/dokuwiki/inc/deprecated.php on line 61
privat_dokuwiki_1        | 172.19.0.9 - - [19/Aug/2020:09:24:52 +0200] "GET /apple-touch-icon.png HTTP/1.0" 500 -
</pre>

It's part of a larger docker-compose, with a nginx reverse proxy in front. I'm not aware of any changes in the setup which would have influence on this. It worked before. It's a bit older installation ( a few months), with automatic container upgrades using watchtower.

**Comment by cybermcm** [comment]
@tuxpeople: please checkout my issue https://github.com/bitnami/bitnami-docker-dokuwiki/issues/78
I'm sure that you ran in an upgrade "bug", possible solution is mentioned here:
https://github.com/bitnami/bitnami-docker-dokuwiki/issues/78#issuecomment-673482662

**Comment by tuxpeople** [comment]
@cybermcm thanks.  You're  right

@rafariossaa I was able to fix it:

1. Downgrade to bitnami/dokuwiki:20180422
2. Upgrade all upgradeable plugins
3. Used the upgrade plugin to upgrade dokuwiki
4. Change to bitnami/dokuwiki:latest

**Comment by rafariossaa** [comment]
Hi @tuxpeople ,
  I am glad you were able to fix it.
  Thanks for sharing your solution.

**Comment by tuxpeople** [comment]
not sure if this needs additional works in the image, but for me it's fixed now.

**Comment by lastb0isct** [comment]
I'm trying to fix this with the same process but am not able to view any of my pages anymore.  I can get to the status page just fine, but all other pages just come up with 404 errors:
```
Not Found
The requested URL was not found on this server.
```

What is the process to upgrade when I can't get to the upgrade plugin page?!

**Comment by carrodher** [comment]
In order to reproduce the issue, @lastb0isct please can you provide the docker-compose you are using to deploy the dokuwiki container? Also, what version are you upgrading from?

**Comment by lastb0isct** [comment]
My docker-compose:
```  dokuwiki:
    image: bitnami/dokuwiki:20180422
    container_name: dokuwiki
    restart: unless-stopped
    networks:
      - dokuwiki-tier
    ports:
      - 8104:8080
      - 8105:8443
    volumes:
      - /mnt/jails/dokuwiki:/bitnami/dokuwiki
```
I was using the :latest tag so I'm not sure what version I was on before...

**Comment by carrodher** [comment]
If you are using the `latest`, I think the issue can be related to the major upgrade in the application itself.

The `latest` tag is always pointing to the more recent version, nowadays the latest version is `20200729` (2020-07-29 “Hogfather”), while some time ago it was the previous major version `20180422` (2018-04-22c “Greebo”). When the Docker image was bumped from the previous major version to the new one, the `latest` tag was also updated pointing to the new one, as there are major changes in the application itself, the upgrade is not guaranteed in those cases, there are some notes about the breaking changes in the [DokuWiki changelog](https://www.dokuwiki.org/changes)

This is the reason behind [rolling VS immutable](https://docs.bitnami.com/kubernetes/infrastructure/apache/configuration/rolling-immutable-tags/) tags and this is why we are not using the `latest` tag by default, i.e https://github.com/bitnami/bitnami-docker-dokuwiki/blob/01971184405d8520d03d2296a512fb26c7fa819c/docker-compose.yml#L4

**Comment by lastb0isct** [comment]
> If you are using the `latest`, I think the issue can be related to the major upgrade in the application itself.
> 
> The `latest` tag is always pointing to the more recent version, nowadays the latest version is `20200729` (2020-07-29 “Hogfather”), while some time ago it was the previous major version `20180422` (2018-04-22c “Greebo”). When the Docker image was bumped from the previous major version to the new one, the `latest` tag was also updated pointing to the new one, as there are major changes in the application itself, the upgrade is not guaranteed in those cases, there are some notes about the breaking changes in the [DokuWiki changelog](https://www.dokuwiki.org/changes)
> 
> This is the reason behind [rolling VS immutable](https://docs.bitnami.com/kubernetes/infrastructure/apache/configuration/rolling-immutable-tags/) tags and this is why we are not using the `latest` tag by default, i.e
> 
> https://github.com/bitnami/bitnami-docker-dokuwiki/blob/01971184405d8520d03d2296a512fb26c7fa819c/docker-compose.yml#L4

Thanks for the info @carrodher -- I guess that means that I might be hosed then?  I went back down to the 20180422 version and i'm not able to navigate to any of the pages.  Might just have to migrate my pages to the new version of the container?

**Comment by carrodher** [comment]
There are some applications where it is difficult to upgrade to a new major in a smooth way, probably not because of the application itself but plugins, modules, customizations, etc. If you have a way to migrate your data to a new container and this method works for you I would try this path
