### ISSUE TITLE
Init container fails if Kubernetes has pod security on

### ISSUE THREAD

**Issue by tuxpeople** [bitnami/bitnami-docker-dokuwiki#81]
Yesterday, I deployed Bitnami Dokuwiki via Helm in my Kubernetes cluster.

Cluster is one made and managed by Rancher. I restored a previously used PV (about three days old). I had [pod security on](https://rancher.com/docs/rancher/v2.x/en/admin-settings/pod-security-policies/) and set to restricted. According to Ranchers documentation:

> This policy is based on the Kubernetes [example restricted policy](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/restricted-psp.yaml). It significantly restricts what types of pods can be deployed to a cluster or project. This policy:
> Prevents pods from running as a privileged user and prevents escalation of privileges.
> Validates that server-required security mechanisms are in place (such as restricting what volumes can be mounted to only the core volume types and preventing root supplemental groups from being added).

The init container failed in this setup. As soon as I disabled PSP, it ran trought. Is there a way to fix this from your side?

**Comment by andresbono** [comment]
Hi @tuxpeople, are setting the `volumePermissions.enabled` to `true`? Does it fail for you if you don't provide this flag? Please note that this is meant to be used in particular cases where  `runAsUser` and `fsUser` values do not work:

https://github.com/bitnami/charts/tree/master/bitnami/dokuwiki#volume-permissions-parameters
