### ISSUE TITLE
Readme.md is no consistent about volume path

### ISSUE THREAD

**Issue by n00ris** [bitnami/bitnami-docker-dokuwiki#82]
**Description**

Hello,
it looks like the documentation in the Readme.md is not consistent.
This chapters say that the volume path should be 

` --volume /path/to/dokuwiki-persistence:/bitnami/dokuwiki \`

https://github.com/bitnami/bitnami-docker-dokuwiki#mount-host-directories-as-data-volumes-with-docker-compose
https://github.com/bitnami/bitnami-docker-dokuwiki#step-2-create-the-dokuwiki-the-container-with-host-volumes

But this chapters only say

 `--volume /path/to/dokuwiki-persistence:/bitnami \`

https://github.com/bitnami/bitnami-docker-dokuwiki#environment-variables
https://github.com/bitnami/bitnami-docker-dokuwiki#restoring-a-backup

**Steps to reproduce the issue:**

1. Read the Readme.md

**Describe the results you received:**

I'm confused about the correct entry point for persistent storage

**Describe the results you expected:**

Documentation should be consistent or explain the different use

**Comment by miguelaeh** [comment]
Hi @n00ris ,
The correct one is `/bitnami/dokuwiki`. In the past it was `/bitnami` but we move it to `/bitnami/dokuwiki`. It seems we forgot about this reference.
Regards.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for noticing this, I have modified the README.

Regards,
