### ISSUE TITLE
Redirects to internal port when using a path prefix

### ISSUE THREAD

**Issue by sargreal** [bitnami/bitnami-docker-dokuwiki#90]
**Description**

When adding a path prefix to the Container, it redirects the URL without a trailing slash to a non http url on the internal port with the prefix.

**Steps to reproduce the issue:**

1. Add the path prefix to the container by creating a script with for example the following content
   ```bash
   #!/bin/bash

   # shellcheck disable=SC1091

   set -o errexit
   set -o nounset
   set -o pipefail
   # set -o xtrace # Uncomment this line for debugging purpose

   # Load Generic Libraries
   . /opt/bitnami/scripts/libwebserver.sh

   ensure_web_server_prefix_configuration_exists dokuwiki --type php --prefix /wiki
   ```
2. Add and execute this script in a customized container
   ```Dockerfile
   FROM bitnami/dokuwiki:20200729-debian-10

   USER 0

   COPY root/ /

   RUN /opt/bitnami/scripts/dokuwiki/path_prefix.sh

   USER 1001
   ```
3. Run the container with a custom port mapping
   ```bash
   docker build -t dokuwiki
   docker exec docker run -p 80:8080 dokuwiki
   ```
4. Open browser or curl:
   ```bash
   curl --head localhost/wiki
   ```
   returns
   ```header
   HTTP/1.1 301 Moved Permanently
   Date: Wed, 09 Dec 2020 20:48:29 GMT
   Server: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.25
   Location: http://localhost:8080/wiki/
   Content-Type: text/html; charset=iso-8859-1
   ```

**Describe the results you received:**

For some reason the `/wiki` url redirects to the internal port `localhost:8080/wiki/`

**Describe the results you expected:**

It should redirect from /wiki to /wiki/ without a different port

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue is probably somewhere in the default apache config but I am not super pro in apache to understand what could be happening there. The easy workaround would probably be to just change the apache port, but that does obviously not fix the underlying issue.

From what I can see it should also not just be an issue with the dokuwiki image but also the apache image but I did not try it there.

**Version**

- Version of the base-image:

`bitnami/dokuwiki@sha256:a9b8c3dc8392d09d3960ad4ee15d191bbf0dba2bbd153c979c4dc25112360755` or `bitnami/dokuwiki:20200729.0.0-debian-10-r103`

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 15
  Running: 1
  Paused: 0
  Stopped: 14
 Images: 47
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 7s6fum8xikai80mrr5239cxpe
  Is Manager: true
  ClusterID: tel9adyu4srbg3wzkualag0yq
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.104-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.39GiB
 Name: docker-desktop
 ID: G7EU:YRLC:RBST:NQNV:DYZF:NJQB:PLUR:G7FA:IN7U:2KSP:Q6UU:RJ3R
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 64
  Goroutines: 177
  System Time: 2020-12-09T20:37:39.2651236Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Tried for reproducabilit on Docker for Windows but happens exactly the same on a debian server.

**Comment by marcosbc** [comment]
Hi @sargreal, you can find more information on why this is happening here: https://serverfault.com/questions/664284/apaches-mod-dir-keeps-redirecting-to-wrong-port

Basically the problem is in how Docker's proxy make requests to the Apache server. You have a few options to "fix" this:

* Enabling `UseCanonicalName On` and setting a proper value for `ServerName`
* Adding a redirection with an absolute URL, i.e.: `RedirectMatch ^/wiki$ /wikia/`
* Disabling access with 404 on `/wiki`, forcing to use `/wiki/`: 

    ```apache
    # Bypass mod_dir in order to allow 80->8080 redirections when not using a reverse proxy (example: docker-compose or Kubernetes)
    <LocationMatch "[^/]$">
        DirectorySlash off
    </LocationMatch>
    ```

This is one of the reasons why we don't support URL prefix configurations for PHP apps on Docker/Kubernetes.

**Comment by sargreal** [comment]
Ah thanks for the explanation!
