### ISSUE TITLE
DokuWiki feature request apache for nginx

### ISSUE THREAD

**Issue by damufo** [bitnami/bitnami-docker-dokuwiki#93]
NGINX is more efficient for serving static pages. As bitnami does not yet have a docker for dokuwiki I used the linuxserver.io image. This uses NGINX to serve the dokuwiki and does so more efficiently as memory consumption is much lower
https://docs.linuxserver.io/images/docker-dokuwiki

That’s why I propose that you do the docker image using NGINX instead of apache.

I attach a couple of screenshots of portainer g unhaafica, one from bitnami dokuwiki and another from linuxserver.io

dokuwiki_bitnami_apache (amd64)
![dokuwiki_bitnami_apache](https://user-images.githubusercontent.com/4057369/111280987-be12e080-863c-11eb-85b7-17694b2b7a90.png)

dokuwiki_linuxserver.io_nginx (arm64)
![dokuwiki_linuxserver io_nginx](https://user-images.githubusercontent.com/4057369/111281010-c3702b00-863c-11eb-8b95-695c5ea371ec.png)

dokuwiki_linuxserver.io_nginx (amd64)
![dokuwiki_linuxserver io_nginx_on_amd64](https://user-images.githubusercontent.com/4057369/111283946-ed771c80-863f-11eb-975a-eae48ef55738.png)

Very thanks.

**Comment by miguelaeh** [comment]
Hi @damufo ,
Thank you very much for the suggestion, I will create an internal task to evaluate it, nevertheless, we can't provide an ETA.
Regards.

**Comment by damufo** [comment]
I think in the case of dokuwiki it may be better to use nginx. For now I will stick with the linuxserver.io docker image even though it requires some more configuration.
When you have an image with nginx surely use bitnami again for ease of installation.
Thank you so much for your attention.
