### ISSUE TITLE
Hw to disable HTTPS ?

### ISSUE THREAD

**Issue by sag1** [bitnami/bitnami-docker-dokuwiki#94]
**Description**
I am installing bitnami dokuwiki on Openshift. So i don't need to have https as it will be controlled by Ingress

**Steps to reproduce the issue:**

1. Go to Openshift
2. Deploy **bitnami/dokuwiki:20200729.0.0-debian-10-r205** image

**Describe the results you received:**

Bad Request
Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.

**Describe the results you expected:**

It should work

I tried by commenting 

- **SetEnvIf** in /opt/bitnami/apache/conf/bitnami/bitnami.conf --> Not working
- **SSLEngine** in /opt/bitnami/apache/conf/vhosts/dokuwiki-https-vhost.conf --> not working

**Comment by marcosbc** [comment]
Hi @sag1, we deploy DokuWiki in two ports, HTTP (container port 8080) and HTTPS (container port 8443). If you access on HTTP port 8080 inside the container you will reach the HTTP service, and if you access 8443 you will reach HTTPS, respectively.

I would say that your port mapping is not correct, as it seems like it's mapping HTTPS port 8443 to an external HTTP endpoint (i.e. external/public port 80). Please check that the mapping makes sense.

If you continue finding issues after reviewing the port mapping, please share more information about your configuration.

**Comment by sag1** [comment]
Hi @marcosbc 
The service is exposed on 2 ports(HTTP, HTTPS) as you explained. I created a route https://dokuwiki.xxx.com mapped to the service HTTPS (container port 8443) with the following options 

secure route --> yes
termination type --> edge
insecure traffic --> redirect

Which will be the correct mapping ?

**Comment by marcosbc** [comment]
Hi @sag1, why are you mapping to the container's HTTPS service (container port 8443) if you do not want to access the app via HTTPS? Instead, you should map to the container's HTTP service (container port 8080) if you do not want to access via HTTPS, but only HTTP.

**Comment by sag1** [comment]
Hi @marcosbc 
Yes, it's working now. I just changed my route to access HTTP service instead of HTTPS. 
Thank you for your prompt guidance

**Comment by marcosbc** [comment]
Nice, thanks for sharing!
