### ISSUE TITLE
enhancement 

### ISSUE THREAD

**Issue by guigus76** [bitnami/bitnami-docker-dokuwiki#95]
pls can you add rsync command to this image 
it will be great to have ability to sync from other wiki to this one

**Comment by marcosbc** [comment]
Hi, we would like to further understand your use case. Is `rsync` required by an official functionality of DokuWiki? Or will you use a custom script for that purpose?

If you will use a custom script, have you considered [extending this image](https://github.com/bitnami/bitnami-docker-dokuwiki#extend-this-image) and add `rsync` from your side?
