### ISSUE TITLE
Headers are not found while enabling openid connect

### ISSUE THREAD

**Issue by sag1** [bitnami/bitnami-docker-dokuwiki#97]
**Description**

I extended the dokuwiki image by adding mod_auth_openidc and enabled it via Loadmodules. I am facing 2 issues 

1. Directive `<Location` /> is not accepted in apache conf

2. Remote_user header is not present in php eventhough i can view it in browser 

Steps to reproduce the issue:**

1. Extend image to add apache module
2. Modify dokuwiki-vhost.conf under/opt/bitnami/apache2/conf/vhosts
3. Add thèse lines 

<VirtualHost *:8080>
        OIDCProviderMetadataURL https://dex.localhost/.well-known/openid-configuration
        OIDCClientID $CLIENT_ID
        OIDCClientSecret $CLIENT_SECRET
        OIDCRedirectURI http://localhost:8080/oauth2/callback
        OIDCCryptoPassphrase openshift
        OIDCRemoteClaim sub
      ` <Location `/>`
                AuthType openid-connect
                Require valid-user
                ProxyPreserveHost on
                ProxyPass      http://localhost:8080/
                ProxyPassReverse        http://localhost:8080/
        `<`/Location>`
        <Directory "/opt/bitnami/dokuwiki">
               .........    
</VirtualHost>
**Describe the results you received:**
<Location /oauth2> accepted and it works but no remote_user header

**Describe the results you expected:**
I would like to `have ` <Location `/>` and remote_user header present

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

Do you have an extended image that we can directly check?

**Comment by sag1** [comment]
Hi, 
Yes, here it is

```
FROM bitnami/dokuwiki:20200729.0.0-debian-10-r205

LABEL name="dokuwiki-image" \
    description="Dokuwiki docker image to add vi and apache conf" \

## Change user to perform privileged actions
USER 0
## Install 'vim' and openidc
RUN install_packages vim wget curl libapache2-mod-auth-openidc unzip
## Copy openidc modules into bitnami apache module
RUN whoami && cp /usr/lib/apache2/modules/mod_auth_openidc.so /opt/bitnami/apache2/modules/mod_auth_openidc.so
## Enable openidc module
RUN sed -i '65s/^/LoadModule auth_openidc_module modules\/mod_auth_openidc.so\n/' /opt/bitnami/apache2/conf/httpd.conf

COPY --chown=1001 authremoteuser /opt/bitnami/dokuwiki/lib/plugins/authremoteuser

## Revert to the original non-root user
USER 1001
```

**Comment by sag1** [comment]
Here is the complete dokuwiki-vhost.conf

`<VirtualHost 127.0.0.1:8080 _default_:8080>
  ServerAlias *
  DocumentRoot /opt/bitnami/dokuwiki

  ProxyPreserveHost on
  ProxyRequests     Off
  
  OIDCProviderMetadataURL http://dex.localhost:4190/dex/.well-known/openid-configuration
  OIDCProviderIssuer http://dex.localhost:4190/dex
  OIDCClientID oauth2-proxy
  OIDCClientSecret b2F1dGgyLXByb3h5LWNsaWVudC1zZWNyZXQK
  OIDCScope "openid email profile"
  #OIDCRedirectURI is a vanity URL that must point to a path protected by this module but must NOT point to any content
  OIDCRedirectURI http://localhost:8080/openid/callback
  OIDCCryptoPassphrase 89yYXReS0UgfXX-GpB68sw==
  #Openid connect
  OIDCRemoteUserClaim sub
  OIDCPassClaimsAs both
  
  <Location /openid>
    AuthType openid-connect
    AuthName "Use Openid Connect"
    Require valid-user
    LogLevel debug
    ProxyPass http://localhost:8080/
    ProxyPassReverse http://localhost:8080/
  </Location>

  <Directory "/opt/bitnami/dokuwiki">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    #Enable DokuWiki friendly URLs - Based on https://www.dokuwiki.org/rewrite
    RewriteEngine on
    RewriteRule ^_media/(.*)              lib/exe/fetch.php?media=$1  [QSA,L]
    RewriteRule ^_detail/(.*)             lib/exe/detail.php?media=$1  [QSA,L]
    RewriteRule ^_export/([^/]+)/(.*)     doku.php?do=export_$1&id=$2  [QSA,L]
    RewriteRule ^$                        doku.php  [L]
    RewriteCond %{REQUEST_FILENAME}       !-f
    RewriteCond %{REQUEST_FILENAME}       !-d
    #Fix: DokuWiki rewrite rule affects Apache server-status page and makes it return a DokuWiki 404 page instead
    RewriteCond %{REQUEST_URI}            !^/server-status$
    RewriteRule (.*)                      doku.php?id=$1  [QSA,L]
    RewriteRule ^index.php$               doku.php
  </Directory>
  Include "/opt/bitnami/apache/conf/vhosts/htaccess/dokuwiki-htaccess.conf"
  </VirtualHost>
`

**Comment by javsalgar** [comment]
Hi,

It seems to me that there are elements missing for me to reproduce

```
COPY --chown=1001 authremoteuser /opt/bitnami/dokuwiki/lib/plugins/authremoteuser
```

I also see a dex installation. Do you have the docker compose for that as well? If you could provide a tarball that contains everything for me to reproduce it would be awesome.

**Comment by sag1** [comment]
Hello, 

Thanks for your effort.

AuthRemoteUser is a dokuwiki plugin to get values from REMOTE_USER variable. You can find details here https://www.dokuwiki.org/plugin:authremoteuser. You can comment it for test purposes, first we have to get REMOTE_USER variable in dokuwiki and then we can add it later.

Here is my tarball [bitnami-dokuwiki.gz](https://github.com/bitnami/bitnami-docker-dokuwiki/files/6477785/bitnami-dokuwiki.gz)

**Comment by javsalgar** [comment]
Hi,

Thank you for the tarball. So far, I was able to access using the location openid to the dex login console, and was able to login but it was not reflected in Dokuwiki. About the REMOTE_USER var, it is true that I didn't see it in the phpinfo() page. 

I found this but I'm not sure if it is fully  related as there are other proxies https://serverfault.com/questions/180726/remote-user-through-apache-reverse-proxy

**Comment by javsalgar** [comment]
Hi,

I've been triyng this but I am unable to see the remote user header in the Chrome network inspector. You said that you could see the header in the browser, could you explain me how?

**Comment by sag1** [comment]
Hi, 
You can see the headers OIDC_CLAIM_XXXX in the browser. I am trying to set REMOTE_USER header with OIDC_CLAIM_sub on apache et get it in dokuwiki using **RequestHeader**

<Location /openid>
    AuthType openid-connect
    AuthName "Use Openid Connect"
    Require valid-user
    LogLevel debug
    RequestHeader     set   REMOTE_USER    "expr=%{OIDC_CLAIM_sub}"
    ProxyPass http://localhost:8080/
    ProxyPassReverse http://localhost:8080/
  </Location>

**Comment by javsalgar** [comment]
I would also try to set a custom header instead of remote user to see if it is passed from /openid to dokuwiki. I think there's something we're missing here.
