### ISSUE TITLE
A way to provide options to php.ini file

### ISSUE THREAD

**Issue by DesertRider** [bitnami/bitnami-docker-dokuwiki#98]
Not quite an issue, but you might consider it to be one...

I wanted to know how to add the following option to the php.ini file:

`openssl.cafile=/opt/certs/rootCA_myowninternal_sha256.pem`

As we are using self-sign certificate, it looks like I have to configure the openssl.cafile option. I couldn't find a way to provide it other than a bind mount to /opt/bitnami/php/etc/php.ini. And under AWS Fargate, bind mount aren't an easy way for such a simple thing...

Is there a way to provide this option (environment variable, ...) when starting the container?

**Comment by alvneiayu** [comment]
hi @DesertRider 

I recommend you two different options, the first one is to mount to php.ini in runtime and modify the php.ini (but you told that it is not easy in AWS Fargate) and the second one is to run a sed command to modify the php.ini file. I don't know if you tested the last one option.

Thanks a lot and I hope that I have helped you.

Álvaro

**Comment by DesertRider** [comment]
I haven't found a way to modify it using sed in the container as I can't sudo and root is the owner of the php.ini file.

I build an image based on yours and did a "RUN sed  -i ...... " command to customize it.

Well, I'm no Docker king so there may be a better way of doing...

**Comment by alvneiayu** [comment]
hi @DesertRider 

Sorry I am confused. Including the "RUN sed -i" line in your Dockerfile, did you finally find the way to modify the php.ini or you are having problems?

Thanks a lot and sorry again.

Álvaro

**Comment by DesertRider** [comment]
Sorry for my poor English, 

Yes, I did find the way to modify the php.ini file in my own Dockerfile. This is how it looks like:

```
FROM bitnami/dokuwiki
MAINTAINER "myself"

# Changement au fichier php.ini pour timezone et accepter notre RootCA
RUN sed -i -e 's,^.*openssl.cafile=.*,openssl.cafile=/opt/certs/MyrootCA_sha256.pem,' /opt/bitnami/php/etc/php.ini

```

Making my own image base on binami/dokuwiki works fine, I can upload it in Amazon ECR and use it with Fargate without problem. IMHO, this is not the best way to do it, as I should keep an eye on the evolution of you image to rebuild mine.

This is why I was looking for a way to use the bitnami/dokuwiki:latest image and modify the /opt/bitnami/php/etc/php.ini on runtime. That's why I opened this issue... having a way to provide customization of the php.ini file via environment variables or a file to combined with php.ini would be great, but I'm no Docker pro, so this may not be feasible or not a good approach.

But, yes, I managed to resolved my situation by using my image based on yours.

**Comment by alvneiayu** [comment]
hi @DesertRider 

Well, it is true. We are facing this as a customization in the container like the example shared in the [README](https://github.com/bitnami/bitnami-docker-dokuwiki#extend-this-image). I created an internal task to include a new way to modify the configuration files (in your case php.ini) in Dokuwiki and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks a lot again

Álvaro

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-dokuwiki#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
