### ISSUE TITLE
AuthLDAP Plugin unable to use LDAPS

### ISSUE THREAD

**Issue by phantomsignal1** [bitnami/bitnami-docker-dokuwiki#99]
**Description**

Using the default docker-compose.yml file, I've created a new DokuWiki instance and tried to use the AuthLDAP plugin. I am able to successfully establish an LDAP connection using the insecure 389 port, but when trying to switch to 636 I receive errors saying I'm unable to connect to the LDAP server

**Steps to reproduce the issue:**

Config of dokuwiki.conf/local.php
```
$conf['title'] = 'Wiki'; 
$conf['license'] = 'cc-by-sa'; 
$conf['useacl'] = 1;
$conf['authtype'] = 'authldap';
$conf['superuser'] = '@admin';
$conf['userewrite'] = '1';
$conf['plugin']['authldap']['server'] = 'ldaps://myldapserver.private';
$conf['plugin']['authldap']['port'] = 636;
$conf['plugin']['authldap']['usertree'] = 'ou=USERS,dc=XX,dc=XX';
$conf['plugin']['authldap']['grouptree'] = 'ou=GROUPS,dc=XX,dc=XX';
$conf['plugin']['authldap']['userfilter'] = '(&(uid=%{user})(objectClass=posixAccount))';
$conf['plugin']['authldap']['groupfilter'] = '(&(objectClass=posixGroup)(|(gidNumber=%{gid})(memberUID=%{user})))';
$conf['plugin']['authldap']['version'] = 3;
$conf['plugin']['authldap']['binddn'] = 'cn=BINDACC,ou=USERS,dc=XX,dc=XX';
$conf['plugin']['authldap']['bindpw'] = '<b>XXXXXXX';
$conf['plugin']['authldap']['attributes'] = array();
$conf['plugin']['authldap']['debug'] = 1;
$conf['plugin']['authldap']['modPass'] = 0;
```

**Describe the results you received:**
When attempting to login receive the following error: 
```
LDAP: couldn't connect to LDAP server
Can't contact LDAP server [auth.php:621]
Sorry, username or password was wrong.
```

**Describe the results you expected:**
Login successful

From the host, when running the following command, I get the following output
```
ldapsearch -ZZ -h MYLDAPSERVER.private -D cn=MYBIND -W -b ou=USERS,dc=XX,dc=XX-P 3
ldap_start_tls: Connect error (-11)
        additional info: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (self signed certificate in certificate chain)
```

However, when adding TLS_REQCERT never under /etc/openldap/ldap.conf - it will successfully connect. Can the equivilant be done inside the container?

**Version**

- Output of `docker version`:

```
Docker version 20.10.7, build f0df350

```

- Output of `docker info`:

```
docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: 84113eef6fc27af1b01b3181f31bbaf708715301
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.243-185.433.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
This is running inside of AWS

**Comment by carrodher** [comment]
Please note this container is executed as a non-root user:

https://github.com/bitnami/bitnami-docker-dokuwiki/blob/806f746d8ca8f2f7f23a8a76fafeba49f2daa632/20200729/debian-10/Dockerfile#L34

There can be some issues if you are trying to use privileged ports. [Here](https://docs.bitnami.com/tutorials/bitnami-best-practices-hardening-containers/#root-and-non-root-containers) you can find more information about root and non-root containers and how you can change the user running the container in the _docker-compose.yaml_
